# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""Stable codes for governance errors and UI hints (spec §21 alignment)."""


class PlanActivate:
	NOT_ALL_PACKAGES_APPROVED = "PP_PLAN_ACTIVATE_NOT_ALL_APPROVED"
	NO_ACTIVE_PACKAGES = "PP_PLAN_ACTIVATE_NO_ACTIVE_PACKAGES"


# Back-compat alias for callers not yet migrated.
class PlanSubmit(PlanActivate):
	pass


class PackageRelease:
	PLAN_NOT_ACTIVE = "PP_RELEASE_PLAN_NOT_ACTIVE"
	MUST_USE_WORKFLOW = "PP_RELEASE_MUST_USE_WORKFLOW"
	# Back-compat alias
	PLAN_NOT_APPROVED = PLAN_NOT_ACTIVE


class DemandInclusion:
	DEMAND_NOT_APPROVED = "PP2-BLOCK-DEMAND-NOT-APPROVED"
	BUDGET_MISSING = "PP2-BLOCK-BUDGET-MISSING"
	DEMAND_ITEM_ALREADY_PACKAGED = "PP2-BLOCK-DEMAND-ITEM-ALREADY-PACKAGED"
	PLAN_INACTIVE = "PP2-BLOCK-PLAN-INACTIVE"


class PackageFromInclusion:
	INCLUSION_NOT_FOUND = "PP2-BLOCK-INCLUSION-NOT-FOUND"
	INCLUSION_INVALID = "PP2-BLOCK-INCLUSION-INVALID"
	TEMPLATE_MISSING = "PP2-BLOCK-TEMPLATE-MISSING"


class PackageMethodDecision:
	PACKAGE_NOT_FOUND = "PP2-BLOCK-PACKAGE-NOT-FOUND"
	LOCKED_AFTER_RELEASE = "PP2-BLOCK-LOCKED-AFTER-RELEASE"
	NO_PACKAGE_LINE = "PP2-BLOCK-NO-PACKAGE-LINE"
	STD_CATEGORY_MISSING = "PP2-BLOCK-STD-CATEGORY-MISSING"
	METHOD_OVERRIDE_REASON = "PP2-BLOCK-METHOD-OVERRIDE-REASON"
	METHOD_MISSING = "PP2-BLOCK-METHOD-MISSING"


class PackageReadiness:
	PACKAGE_NOT_FOUND = "PP2-BLOCK-PACKAGE-NOT-FOUND"
	LOCKED_AFTER_RELEASE = "PP2-BLOCK-LOCKED-AFTER-RELEASE"
	READINESS_FAILED = "PP2-BLOCK-READINESS-FAILED"
	READINESS_STALE = "PP2-BLOCK-READINESS-STALE"


class PackageSubmitReview:
	PACKAGE_NOT_FOUND = "PP2-BLOCK-PACKAGE-NOT-FOUND"
	INVALID_STATE = "PP2-BLOCK-INVALID-STATE"
	LOCKED_AFTER_RELEASE = "PP2-BLOCK-LOCKED-AFTER-RELEASE"
	NO_PACKAGE_LINE = "PP2-BLOCK-NO-PACKAGE-LINE"
	PACKAGE_NOT_COMPLETE = "PP2-BLOCK-PACKAGE-NOT-COMPLETE"


class PackageReviewDecision:
	PACKAGE_NOT_FOUND = "PP2-BLOCK-PACKAGE-NOT-FOUND"
	INVALID_STATE = "PP2-BLOCK-INVALID-STATE"
	LOCKED_AFTER_RELEASE = "PP2-BLOCK-LOCKED-AFTER-RELEASE"
	PACKAGE_NOT_COMPLETE = "PP2-BLOCK-PACKAGE-NOT-COMPLETE"
	SELF_APPROVAL_NOT_ALLOWED = "PP2-BLOCK-SELF-APPROVAL"
	RETURN_REASON_REQUIRED = "PP2-BLOCK-RETURN-REASON-REQUIRED"
	RETURN_CORRECTION_REQUIRED = "PP2-BLOCK-RETURN-CORRECTION-REQUIRED"
	INVALID_DECISION = "PP2-BLOCK-INVALID-DECISION"


class PackageMarkReady:
	PACKAGE_NOT_FOUND = "PP2-BLOCK-PACKAGE-NOT-FOUND"
	INVALID_STATE = "PP2-BLOCK-INVALID-STATE"
	LOCKED_AFTER_RELEASE = "PP2-BLOCK-LOCKED-AFTER-RELEASE"
	READINESS_FAILED = "PP2-BLOCK-READINESS-FAILED"
	READINESS_STALE = "PP2-BLOCK-READINESS-STALE"


class PackageReleaseToTender:
	PACKAGE_NOT_FOUND = "PP2-BLOCK-PACKAGE-NOT-FOUND"
	INVALID_STATE = "PP2-BLOCK-INVALID-STATE"
	PLAN_NOT_ACTIVE = "PP2-BLOCK-PLAN-INACTIVE"
	READINESS_FAILED = "PP2-BLOCK-READINESS-FAILED"
	READINESS_STALE = "PP2-BLOCK-READINESS-STALE"
	PACKAGE_NOT_COMPLETE = "PP2-BLOCK-PACKAGE-NOT-COMPLETE"
	HANDOFF_INCOMPLETE = "PP2-BLOCK-HANDOFF-INCOMPLETE"
	XMV_BLOCKED = "PP2-BLOCK-XMV-CRITICAL"


class PackageReleaseConsumed:
	RELEASE_NOT_FOUND = "PP2-BLOCK-RELEASE-NOT-FOUND"
	PACKAGE_NOT_FOUND = "PP2-BLOCK-PACKAGE-NOT-FOUND"
	INVALID_STATE = "PP2-BLOCK-INVALID-STATE"
	RELEASE_STALE = "PP2-BLOCK-RELEASE-STALE"
	TENDER_NOT_FOUND = "PP2-BLOCK-TENDER-NOT-FOUND"
	TENDER_PACKAGE_MISMATCH = "PP2-BLOCK-TENDER-PACKAGE-MISMATCH"
	BASELINE_MISMATCH = "PP2-BLOCK-BASELINE-MISMATCH"


class PackagePostReleaseLock:
	LOCKED_AFTER_RELEASE = "PP2-BLOCK-LOCKED-AFTER-RELEASE"


class PlanningPermission:
	NOT_PERMITTED = "PP2-BLOCK-NOT-PERMITTED"
	OUT_OF_SCOPE = "PP2-BLOCK-OUT-OF-SCOPE"


class PackagePlanningCorrection:
	PACKAGE_NOT_FOUND = "PP2-BLOCK-PACKAGE-NOT-FOUND"
	INVALID_STATE = "PP2-BLOCK-INVALID-STATE"
	REASON_REQUIRED = "PP2-BLOCK-CORRECTION-REASON-REQUIRED"
	AFFECTED_FIELDS_REQUIRED = "PP2-BLOCK-CORRECTION-FIELDS-REQUIRED"
	RELEASE_CODE_REQUIRED = "PP2-BLOCK-RELEASE-CODE-REQUIRED"
	REPLACEMENT_REQUIRED = "PP2-BLOCK-SUPERSESSION-REPLACEMENT-MISSING"
	REPLACEMENT_INVALID = "PP2-BLOCK-SUPERSESSION-REPLACEMENT-INVALID"
	INVALID_CORRECTION_TYPE = "PP2-BLOCK-INVALID-CORRECTION-TYPE"
