# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""C2 — Apply a Procurement Template to demands under a Draft plan (Cursor Pack C2)."""

from __future__ import annotations

import secrets
from collections import defaultdict

import frappe
from frappe import _
from frappe.utils import cint, flt
from frappe.utils.data import parse_json

from kentender_procurement.procurement_planning.doctype.procurement_package.procurement_package import (
	recompute_package_estimated_value,
)
from kentender_procurement.procurement_planning.services.template_applicability import (
	validate_demands_for_template,
)

# Demand fieldnames allowed in template grouping_strategy.group_by (v1).
# "department" is accepted as an alias for requesting_department (Demand label).
_GROUP_BY_CANONICAL = {
	"demand_type": "demand_type",
	"requisition_type": "requisition_type",
	"procuring_entity": "procuring_entity",
	"requesting_department": "requesting_department",
	"department": "requesting_department",
}


def _parse_grouping_strategy(raw) -> list[str]:
	if raw in (None, ""):
		return []
	parsed = parse_json(raw) if isinstance(raw, str) else raw
	if not isinstance(parsed, dict):
		frappe.throw(_("Grouping strategy must be a JSON object."), title=_("Invalid template"))
	group_by = parsed.get("group_by")
	if group_by is None:
		return []
	if not isinstance(group_by, list):
		frappe.throw(_("grouping_strategy.group_by must be a JSON list."), title=_("Invalid template"))
	return [str(x).strip() for x in group_by if str(x).strip()]


def _normalize_group_by_keys(keys: list[str]) -> list[str]:
	out: list[str] = []
	for k in keys:
		if k not in _GROUP_BY_CANONICAL:
			frappe.throw(
				_("Unknown grouping field {0}. Allowed: {1}.").format(
					k, ", ".join(sorted(set(_GROUP_BY_CANONICAL.keys())))
				),
				title=_("Invalid grouping"),
			)
		canon = _GROUP_BY_CANONICAL[k]
		if canon not in out:
			out.append(canon)
	return out


def _group_demands(demand_ids: list[str], group_fields: list[str]) -> list[list[str]]:
	if not group_fields:
		return [list(demand_ids)]

	fields = ["name", *group_fields]
	rows = frappe.get_all("Demand", filters={"name": ["in", demand_ids]}, fields=fields, order_by="name")
	if len(rows) != len(set(demand_ids)):
		frappe.throw(_("One or more demands could not be loaded."), title=_("Invalid demand"))

	buckets: dict[tuple, list[str]] = defaultdict(list)
	for row in rows:
		key = tuple(row.get(f) or "" for f in group_fields)
		buckets[key].append(row.name)

	order_index = {d: i for i, d in enumerate(demand_ids)}
	return sorted(buckets.values(), key=lambda g: min(order_index[x] for x in g))


def _unique_package_code(plan_code: str | None) -> str:
	base = (plan_code or "PKG").strip().replace(" ", "-")[:28] or "PKG"
	for _ in range(64):
		code = f"{base}-{secrets.token_hex(3).upper()}"
		if not frappe.db.exists("Procurement Package", {"package_code": code}):
			return code
	frappe.throw(_("Could not allocate a unique package code."), title=_("Naming error"))


def _package_name_for_group(template_name: str, group_fields: list[str], group_key: tuple) -> str:
	if not group_fields:
		return template_name
	parts = [str(v) for v in group_key if v]
	suffix = " / ".join(parts) if parts else "group"
	return f"{template_name} — {suffix}"[:140]


def apply_template_to_demands(
	plan_id: str,
	template_id: str,
	demand_ids: list[str],
	actor: str | None = None,
	options: dict | None = None,
) -> dict:
	"""Create Procurement Package(s) and line(s) from demands; never mutates Demand.

	v1: line amount is Demand.total_amount (see implementation tracker if PRD differs).

	Optional ``options`` (seed / smoke only, not for production workbench UX):

	- ``package_code`` and ``package_name`` (both required if either is set): used instead of
	  autogenerated values when grouping yields **exactly one** package; otherwise raises.
	"""
	if not plan_id:
		frappe.throw(_("Procurement Plan is required."), title=_("Missing plan"))
	if not template_id:
		frappe.throw(_("Procurement Template is required."), title=_("Missing template"))

	plan = frappe.get_doc("Procurement Plan", plan_id)
	if plan.status not in ("Draft", "Returned"):
		frappe.throw(
			_('Procurement Plan must be Draft or Returned to apply a template (current: {0}).').format(
				plan.status or ""
			),
			title=_("Invalid state"),
		)

	seen: list[str] = []
	uniq: list[str] = []
	for d in demand_ids or []:
		d = (d or "").strip()
		if not d:
			continue
		if d not in seen:
			seen.append(d)
			uniq.append(d)
	if not uniq:
		frappe.throw(_("At least one demand is required."), title=_("Missing demands"))

	tmpl = frappe.get_doc("Procurement Template", template_id)
	if tmpl.get("is_active") is not None and cint(tmpl.is_active) == 0:
		frappe.throw(_("Procurement Template is not active."), title=_("Inactive template"))

	validate_demands_for_template(template_id, uniq)

	group_by_raw = _parse_grouping_strategy(tmpl.grouping_strategy)
	group_fields = _normalize_group_by_keys(group_by_raw)
	groups = _group_demands(uniq, group_fields)

	opt = options or {}
	fx_code = (opt.get("package_code") or "").strip()
	fx_name = (opt.get("package_name") or "").strip()
	if fx_code or fx_name:
		if not (fx_code and fx_name):
			frappe.throw(
				_("package_code and package_name must both be set when using fixed package options."),
				title=_("Invalid options"),
			)
		if len(groups) != 1:
			frappe.throw(
				_("Fixed package_code/package_name apply only when grouping yields a single package."),
				title=_("Invalid options"),
			)

	created_by = (actor or "").strip() or frappe.session.user
	packages_out: list[dict] = []
	lines_created = 0

	frappe.flags.skip_package_line_rollup = True
	try:
		for demand_group in groups:
			if group_fields:
				sample = frappe.db.get_value("Demand", demand_group[0], group_fields, as_dict=True)
				gkey = tuple((sample or {}).get(f) or "" for f in group_fields)
			else:
				gkey = tuple()

			if fx_code and fx_name:
				pkg_code, pkg_name = fx_code, fx_name
			else:
				pkg_code = _unique_package_code(plan.plan_code)
				pkg_name = _package_name_for_group(tmpl.template_name, group_fields, gkey)

			pkg = frappe.get_doc(
				{
					"doctype": "Procurement Package",
					"plan_id": plan_id,
					"template_id": template_id,
					"package_code": pkg_code,
					"package_name": pkg_name,
					"status": "Draft",
					"procurement_method": tmpl.default_method,
					"contract_type": tmpl.default_contract_type,
					"currency": plan.currency,
					"risk_profile_id": tmpl.risk_profile_id,
					"kpi_profile_id": tmpl.kpi_profile_id,
					"decision_criteria_profile_id": tmpl.decision_criteria_profile_id,
					"vendor_management_profile_id": tmpl.vendor_management_profile_id,
					"method_override_flag": 0,
					"created_by": created_by,
				}
			)
			pkg.insert(ignore_permissions=True)

			for demand_id in demand_group:
				d = frappe.db.get_value(
					"Demand",
					demand_id,
					("budget_line", "total_amount", "requesting_department", "priority_level"),
					as_dict=True,
				)
				line = frappe.get_doc(
					{
						"doctype": "Procurement Package Line",
						"package_id": pkg.name,
						"demand_id": demand_id,
						"budget_line_id": d.budget_line,
						"amount": flt(d.total_amount),
						"quantity": 1.0,
						"department": d.requesting_department or None,
						"priority": d.priority_level or "Normal",
						"is_active": 1,
					}
				)
				line.insert(ignore_permissions=True)
				lines_created += 1

			recompute_package_estimated_value(pkg.name)
			packages_out.append({"name": pkg.name, "package_code": pkg.package_code})
	finally:
		frappe.flags.pop("skip_package_line_rollup", None)

	return {"packages": packages_out, "lines_created": lines_created}
