# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""STD Engine Milestone 1 constants — lifecycle, UI mode, canonical seed identity."""

from __future__ import annotations

FRAPPE_MODULE = "STD Engine"

CANONICAL_FAMILY_CODE = "KE-PPRA-IT"
CANONICAL_PACKAGE_ID = "KE-PPRA-IT-2022-04"
CANONICAL_VERSION_CODE = "KE-PPRA-IT-2022-04"

COMMIT_TARGET_STATE_M1 = "DRAFT"
UI_MODE_READ_ONLY_INSPECTION = "READ_ONLY_INSPECTION"
UI_MODE_ACTIVE_TEMPLATE = "ACTIVE_TEMPLATE"

FIXTURE_SOURCE_SMOKE_TEST_EXPECTATION = "SMOKE_TEST_EXPECTATION"
FIXTURE_SOURCE_CONSUMER_BINDING = "CONSUMER_BINDING"
FIXTURE_SOURCE_NSSF_CALIBRATION = "NSSF_CALIBRATION_FIXTURE"

LEGAL_REVIEW_APPROVED = "LEGAL_REVIEW_APPROVED"

NSSF_FIXTURE_CODE = "NSSF-SPS-ERP-2025-2026"
NSSF_TENDER_REF = "NSSFSPS/ICT/ERP/001/2025-2026"

LIFECYCLE_STATES: tuple[str, ...] = (
	"DRAFT",
	"STRUCTURING",
	"INTERNAL_REVIEW",
	"LEGAL_REVIEW",
	"PROCUREMENT_REVIEW",
	"APPROVED",
	"ACTIVE",
	"SUPERSEDED",
	"ARCHIVED",
)

PACKAGE_QUALITY_RECONCILED_DRAFT = "RECONCILED_DRAFT_NOT_ACTIVATABLE"
PACKAGE_QUALITY_FULL_EXTRACTION = "FULL_EXTRACTION_CANDIDATE"
