# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""Audit event catalogue constants — SEC-0510 / std engine §13.

Centralizes pack event codes so security hardening services avoid ad-hoc strings.
"""

from __future__ import annotations

from enum import StrEnum


class AuditEventCode(StrEnum):
	# --- STD Library / Template --------------------------------------------
	STD_PACKAGE_IMPORTED = "STD_PACKAGE_IMPORTED"
	STD_SOURCE_REGISTERED = "STD_SOURCE_REGISTERED"
	STD_TEMPLATE_VALIDATED = "STD_TEMPLATE_VALIDATED"
	STD_TEMPLATE_VALIDATION_BLOCKED = "STD_TEMPLATE_VALIDATION_BLOCKED"
	STD_TEMPLATE_SUBMITTED_REVIEW = "STD_TEMPLATE_SUBMITTED_REVIEW"
	STD_TEMPLATE_APPROVED = "STD_TEMPLATE_APPROVED"
	STD_TEMPLATE_ACTIVATED = "STD_TEMPLATE_ACTIVATED"
	STD_TEMPLATE_SUPERSEDED = "STD_TEMPLATE_SUPERSEDED"
	STD_TEMPLATE_ADVANCED_EDIT = "STD_TEMPLATE_ADVANCED_EDIT"
	STD_TEMPLATE_EDIT_DENIED = "STD_TEMPLATE_EDIT_DENIED"

	# --- Planning-to-Tender Release ----------------------------------------
	RELEASE_ELIGIBILITY_CHECKED = "RELEASE_ELIGIBILITY_CHECKED"
	RELEASE_BLOCKED = "RELEASE_BLOCKED"
	RELEASE_STD_OPTION_SELECTED = "RELEASE_STD_OPTION_SELECTED"
	RELEASE_TENDER_CREATED = "RELEASE_TENDER_CREATED"
	RELEASE_STD_INSTANCE_CREATED = "RELEASE_STD_INSTANCE_CREATED"
	RELEASE_STD_BINDING_CREATED = "RELEASE_STD_BINDING_CREATED"
	RELEASE_COMPLETED = "RELEASE_COMPLETED"
	RELEASE_PERMISSION_DENIED = "RELEASE_PERMISSION_DENIED"

	# --- STD Instance Completion -------------------------------------------
	STD_INSTANCE_CREATED = "STD_INSTANCE_CREATED"
	STD_PARAMETER_CHANGED = "STD_PARAMETER_CHANGED"
	STD_ATTACHMENT_ADDED = "STD_ATTACHMENT_ADDED"
	STD_WORKS_REQUIREMENT_CHANGED = "STD_WORKS_REQUIREMENT_CHANGED"
	STD_DRAWING_REGISTER_CHANGED = "STD_DRAWING_REGISTER_CHANGED"
	STD_BOQ_CHANGED = "STD_BOQ_CHANGED"
	STD_OUTPUTS_GENERATED = "STD_OUTPUTS_GENERATED"
	STD_OUTPUT_MARKED_STALE = "STD_OUTPUT_MARKED_STALE"
	STD_READINESS_RUN = "STD_READINESS_RUN"
	STD_READINESS_BLOCKED = "STD_READINESS_BLOCKED"
	STD_CONFIGURATION_SNAPSHOT_CREATED = "STD_CONFIGURATION_SNAPSHOT_CREATED"
	STD_LOCKED_FOR_APPROVAL = "STD_LOCKED_FOR_APPROVAL"

	# --- Derived Models -----------------------------------------------------
	DERIVED_MODEL_GENERATED = "DERIVED_MODEL_GENERATED"
	DERIVED_MODEL_GENERATION_FAILED = "DERIVED_MODEL_GENERATION_FAILED"
	DERIVED_MODEL_MARKED_STALE = "DERIVED_MODEL_MARKED_STALE"
	DERIVED_MODEL_SUPERSEDED = "DERIVED_MODEL_SUPERSEDED"
	DERIVED_MODEL_CONSUMED = "DERIVED_MODEL_CONSUMED"
	DERIVED_MODEL_CONSUMPTION_DENIED = "DERIVED_MODEL_CONSUMPTION_DENIED"
	MANUAL_RULE_INJECTION_DENIED = "MANUAL_RULE_INJECTION_DENIED"

	# --- Approval / Publication --------------------------------------------
	PUBLICATION_READINESS_RUN = "PUBLICATION_READINESS_RUN"
	PUBLICATION_READINESS_BLOCKED = "PUBLICATION_READINESS_BLOCKED"
	TENDER_SUBMITTED_FOR_APPROVAL = "TENDER_SUBMITTED_FOR_APPROVAL"
	APPROVAL_REVIEW_OPENED = "APPROVAL_REVIEW_OPENED"
	APPROVAL_RETURNED = "APPROVAL_RETURNED"
	APPROVAL_REJECTED = "APPROVAL_REJECTED"
	APPROVAL_GRANTED = "APPROVAL_GRANTED"
	PUBLICATION_ATTEMPTED = "PUBLICATION_ATTEMPTED"
	PUBLICATION_DENIED = "PUBLICATION_DENIED"
	PUBLICATION_SNAPSHOT_CREATED = "PUBLICATION_SNAPSHOT_CREATED"
	TENDER_PUBLISHED = "TENDER_PUBLISHED"
	POST_PUBLICATION_EDIT_DENIED = "POST_PUBLICATION_EDIT_DENIED"

	# --- Evidence / Audit ---------------------------------------------------
	EVIDENCE_PACKAGE_ASSEMBLED = "EVIDENCE_PACKAGE_ASSEMBLED"
	EVIDENCE_PACKAGE_EXPORTED = "EVIDENCE_PACKAGE_EXPORTED"
	AUDIT_LOG_VIEWED = "AUDIT_LOG_VIEWED"
	AUDIT_EXPORT_DENIED = "AUDIT_EXPORT_DENIED"
	ACTION_AVAILABILITY_DENIED = "ACTION_AVAILABILITY_DENIED"


STD_LIBRARY_TEMPLATE_EVENTS: frozenset[str] = frozenset(
	{
		AuditEventCode.STD_PACKAGE_IMPORTED,
		AuditEventCode.STD_SOURCE_REGISTERED,
		AuditEventCode.STD_TEMPLATE_VALIDATED,
		AuditEventCode.STD_TEMPLATE_VALIDATION_BLOCKED,
		AuditEventCode.STD_TEMPLATE_SUBMITTED_REVIEW,
		AuditEventCode.STD_TEMPLATE_APPROVED,
		AuditEventCode.STD_TEMPLATE_ACTIVATED,
		AuditEventCode.STD_TEMPLATE_SUPERSEDED,
		AuditEventCode.STD_TEMPLATE_ADVANCED_EDIT,
		AuditEventCode.STD_TEMPLATE_EDIT_DENIED,
	}
)

RELEASE_EVENTS: frozenset[str] = frozenset(
	{
		AuditEventCode.RELEASE_ELIGIBILITY_CHECKED,
		AuditEventCode.RELEASE_BLOCKED,
		AuditEventCode.RELEASE_STD_OPTION_SELECTED,
		AuditEventCode.RELEASE_TENDER_CREATED,
		AuditEventCode.RELEASE_STD_INSTANCE_CREATED,
		AuditEventCode.RELEASE_STD_BINDING_CREATED,
		AuditEventCode.RELEASE_COMPLETED,
		AuditEventCode.RELEASE_PERMISSION_DENIED,
	}
)

STD_INSTANCE_COMPLETION_EVENTS: frozenset[str] = frozenset(
	{
		AuditEventCode.STD_INSTANCE_CREATED,
		AuditEventCode.STD_PARAMETER_CHANGED,
		AuditEventCode.STD_ATTACHMENT_ADDED,
		AuditEventCode.STD_WORKS_REQUIREMENT_CHANGED,
		AuditEventCode.STD_DRAWING_REGISTER_CHANGED,
		AuditEventCode.STD_BOQ_CHANGED,
		AuditEventCode.STD_OUTPUTS_GENERATED,
		AuditEventCode.STD_OUTPUT_MARKED_STALE,
		AuditEventCode.STD_READINESS_RUN,
		AuditEventCode.STD_READINESS_BLOCKED,
		AuditEventCode.STD_CONFIGURATION_SNAPSHOT_CREATED,
		AuditEventCode.STD_LOCKED_FOR_APPROVAL,
	}
)

DERIVED_MODEL_EVENTS: frozenset[str] = frozenset(
	{
		AuditEventCode.DERIVED_MODEL_GENERATED,
		AuditEventCode.DERIVED_MODEL_GENERATION_FAILED,
		AuditEventCode.DERIVED_MODEL_MARKED_STALE,
		AuditEventCode.DERIVED_MODEL_SUPERSEDED,
		AuditEventCode.DERIVED_MODEL_CONSUMED,
		AuditEventCode.DERIVED_MODEL_CONSUMPTION_DENIED,
		AuditEventCode.MANUAL_RULE_INJECTION_DENIED,
	}
)

APPROVAL_PUBLICATION_EVENTS: frozenset[str] = frozenset(
	{
		AuditEventCode.PUBLICATION_READINESS_RUN,
		AuditEventCode.PUBLICATION_READINESS_BLOCKED,
		AuditEventCode.TENDER_SUBMITTED_FOR_APPROVAL,
		AuditEventCode.APPROVAL_REVIEW_OPENED,
		AuditEventCode.APPROVAL_RETURNED,
		AuditEventCode.APPROVAL_REJECTED,
		AuditEventCode.APPROVAL_GRANTED,
		AuditEventCode.PUBLICATION_ATTEMPTED,
		AuditEventCode.PUBLICATION_DENIED,
		AuditEventCode.PUBLICATION_SNAPSHOT_CREATED,
		AuditEventCode.TENDER_PUBLISHED,
		AuditEventCode.POST_PUBLICATION_EDIT_DENIED,
	}
)

EVIDENCE_AUDIT_EVENTS: frozenset[str] = frozenset(
	{
		AuditEventCode.EVIDENCE_PACKAGE_ASSEMBLED,
		AuditEventCode.EVIDENCE_PACKAGE_EXPORTED,
		AuditEventCode.AUDIT_LOG_VIEWED,
		AuditEventCode.AUDIT_EXPORT_DENIED,
		AuditEventCode.ACTION_AVAILABILITY_DENIED,
	}
)

ALL_AUDIT_EVENT_CODES: frozenset[str] = frozenset(
	STD_LIBRARY_TEMPLATE_EVENTS
	| RELEASE_EVENTS
	| STD_INSTANCE_COMPLETION_EVENTS
	| DERIVED_MODEL_EVENTS
	| APPROVAL_PUBLICATION_EVENTS
	| EVIDENCE_AUDIT_EVENTS
)


def is_known_audit_event_code(value: str) -> bool:
	return (value or "").strip() in ALL_AUDIT_EVENT_CODES
