# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""DERIVED-1100 — Pack §18 derived-model audit ``event_type`` codes (canonical strings)."""

from __future__ import annotations

from kentender_procurement.tender_management.security.authorization.denial_codes import (
	DenialCode,
)
from kentender_procurement.tender_management.security.audit.event_catalog import (
	AuditEventCode,
)

DERIVED_MODEL_GENERATION_REQUESTED = "DERIVED_MODEL_GENERATION_REQUESTED"
DERIVED_MODEL_GENERATED = AuditEventCode.DERIVED_MODEL_GENERATED
DERIVED_MODEL_GENERATION_FAILED = AuditEventCode.DERIVED_MODEL_GENERATION_FAILED
DERIVED_MODEL_MARKED_STALE = AuditEventCode.DERIVED_MODEL_MARKED_STALE
DERIVED_MODEL_SUPERSEDED = AuditEventCode.DERIVED_MODEL_SUPERSEDED
DERIVED_MODEL_CONSUMED = AuditEventCode.DERIVED_MODEL_CONSUMED
DERIVED_MODEL_CONSUMPTION_DENIED = AuditEventCode.DERIVED_MODEL_CONSUMPTION_DENIED

MANUAL_SUBMISSION_REQUIREMENT_DENIED = DenialCode.MANUAL_SUBMISSION_REQUIREMENT_DENIED
MANUAL_OPENING_EVALUATION_FIELD_DENIED = DenialCode.MANUAL_OPENING_EVALUATION_FIELD_DENIED
MANUAL_EVALUATION_CRITERIA_DENIED = DenialCode.MANUAL_EVALUATION_CRITERIA_DENIED
# Audit ``event_type`` namespace (DERIVED-1100); distinct suffix from pack ``CONTRACT_BINDING_VIOLATION``.
CONTRACT_BINDING_VIOLATION_DENIED = "CONTRACT_BINDING_VIOLATION_DENIED"

ADDENDUM_DERIVED_MODELS_REGENERATED = "ADDENDUM_DERIVED_MODELS_REGENERATED"
