<!-- REQ-DES-10 Authorised Requisition (§13.12), ported class-for-class: the
     eyebrow+title+status+reference (with handoff id) header, the "Open
     Tender Preparation" action in the masthead's own corner, Planning-
     drawdown and Tender-status cards, the Budget-reservations table (real
     reservation/Budget-Line references, never internal docnames), the
     complete-structured-package summary cards, the authorised-by line, the
     digest line, and the Revoke action — hidden entirely once consumed,
     never merely disabled (§13.12: "Hide revocation action after
     consumption"). -->
<template>
	<div class="req-step-content">
		<div class="req-masthead">
			<div class="req-editor-titlebar">
				<div class="kt-eyebrow">AUTHORISED REQUISITION</div>
				<button v-if="handoff.consumption && !handoff.consumption.consumed_at" type="button" class="kt-btn kt-btn-primary req-open-tender" data-testid="req-open-tender" @click="$emit('open-tender')">Open Tender Preparation</button>
			</div>
			<div class="req-editor-titlebar">
				<h1 class="req-editor-title">{{ (handoff.payload || {}).requirement_title }}</h1>
				<span class="kt-status is-live">Authorised for Tender Preparation</span>
			</div>
			<div class="req-editor-reference">{{ reference }}</div>
		</div>

		<div class="req-field-grid">
			<div class="kt-card kt-blueprint req-card-pad">
				<i class="kt-corner tl"></i><i class="kt-corner tr"></i><i class="kt-corner bl"></i><i class="kt-corner br"></i>
				<div class="kt-eyebrow">Planning drawdown</div>
				<div class="req-summary-title">{{ (handoff.requisition || {}).plan_item_id }}</div>
				<p class="req-context-body">{{ sourceLineIds }}</p>
			</div>
			<div class="kt-card kt-blueprint req-card-pad">
				<i class="kt-corner tl"></i><i class="kt-corner tr"></i><i class="kt-corner bl"></i><i class="kt-corner br"></i>
				<div class="kt-eyebrow">Tender status</div>
				<div class="req-summary-title">
					<span class="kt-status" :class="isConsumed ? 'is-live' : 'is-pending'">{{ isConsumed ? consumedLabel : "Not yet consumed" }}</span>
				</div>
			</div>
		</div>

		<div class="kt-card-title">Budget reservations</div>
		<table class="kt-table" data-testid="req-reservations-table">
			<thead>
				<tr>
					<th>Reservation</th>
					<th>Drawdown line</th>
					<th class="req-num">Value</th>
					<th>Budget Line</th>
				</tr>
			</thead>
			<tbody>
				<tr v-for="row in drawdownDisplay" :key="row.reservation_label">
					<td>{{ row.reservation_label }}</td>
					<td>{{ row.organisation_unit_label }}</td>
					<td class="req-num">{{ money(row.requested_value) }}</td>
					<td>{{ row.budget_line_label }}</td>
				</tr>
			</tbody>
		</table>

		<div class="kt-card-title">Complete structured package</div>
		<div class="req-summary-grid">
			<div class="kt-card kt-blueprint req-card-pad-tight">
				<i class="kt-corner tl"></i><i class="kt-corner tr"></i><i class="kt-corner bl"></i><i class="kt-corner br"></i>
				<div class="kt-eyebrow">Equipment</div>
				<div class="req-summary-title">{{ packageSummary.items || 0 }} item{{ (packageSummary.items || 0) === 1 ? "" : "s" }}</div>
			</div>
			<div class="kt-card kt-blueprint req-card-pad-tight">
				<i class="kt-corner tl"></i><i class="kt-corner tr"></i><i class="kt-corner bl"></i><i class="kt-corner br"></i>
				<div class="kt-eyebrow">Technical requirements</div>
				<div class="req-summary-title">{{ packageSummary.technical_requirements || 0 }} row{{ (packageSummary.technical_requirements || 0) === 1 ? "" : "s" }}</div>
			</div>
			<div class="kt-card kt-blueprint req-card-pad-tight">
				<i class="kt-corner tl"></i><i class="kt-corner tr"></i><i class="kt-corner bl"></i><i class="kt-corner br"></i>
				<div class="kt-eyebrow">Acceptance</div>
				<div class="req-summary-title">{{ packageSummary.acceptance_requirements || 0 }} row{{ (packageSummary.acceptance_requirements || 0) === 1 ? "" : "s" }}</div>
			</div>
		</div>

		<p v-if="authorisedBy.name" class="req-table-caption">Authorised by {{ authorisedBy.name }}, {{ authorisedBy.role }} · {{ authorisedBy.decided_at }}</p>
		<p class="req-table-caption">Authorised version digest — Generated by KenTender · <span class="req-digest">{{ handoff.handoff_digest }}</span></p>

		<div v-if="handoff.can_revoke" class="req-actions">
			<button type="button" class="kt-btn kt-btn-secondary kt-danger" :disabled="pending" data-testid="req-revoke" @click="$emit('revoke')">Revoke authorisation</button>
		</div>
	</div>
</template>

<script setup>
import { computed } from "vue";
import { formatMoney } from "../data/format.js";

const props = defineProps({
	handoff: { type: Object, required: true },
	pending: Boolean,
});

defineEmits(["open-tender", "revoke"]);

const reference = computed(() => {
	const r = props.handoff.requisition || {};
	return [r.requisition_reference, r.plan_item_id, `Handoff ${props.handoff.handoff}`].filter(Boolean).join(" · ");
});

const drawdownDisplay = computed(() => props.handoff.drawdown_display || []);
const packageSummary = computed(() => props.handoff.package_summary || {});
const authorisedBy = computed(() => props.handoff.authorised_by || {});
const isConsumed = computed(() => !!(props.handoff.consumption || {}).consumed_at);
const consumedLabel = computed(() => {
	const c = props.handoff.consumption || {};
	return `Consumed by ${c.tender} · ${c.template_key} ${c.template_version}`;
});

const sourceLineIds = computed(() => {
	const lines = (props.handoff.payload || {}).drawdown_lines || [];
	return [...new Set(lines.map((l) => l.source_line_id).filter(Boolean))].join(" · ");
});

function money(amount) {
	return formatMoney(amount);
}
</script>
