<!-- REQ-DES-08 Department approval task (§13.10), ported class-for-class:
     the eyebrow+title+status+reference header, "Prepared by" line, three
     summary cards, drawdown table, items table, technical-requirements
     table, content digest line, the italic certification statement card,
     the "Decision by" line, and Return/Submit footer. No edit control —
     this is a read-only certification screen (§13.10: "No edit control"). -->
<template>
	<div class="req-step-content">
		<div class="req-masthead">
			<div class="kt-eyebrow">DEPARTMENT APPROVAL</div>
			<div class="req-editor-titlebar">
				<h1 class="req-editor-title">{{ (task.version || {}).requirement_title }}</h1>
				<span class="kt-status is-pending">Awaiting Department Approval</span>
			</div>
			<div class="req-editor-reference">{{ reference }}</div>
			<p class="req-prepared-by">Prepared by <strong>{{ (task.prepared_by || {}).name }}</strong>, {{ (task.prepared_by || {}).role }}</p>
		</div>

		<div class="req-summary-grid">
			<div class="kt-card kt-blueprint req-card-pad-tight">
				<i class="kt-corner tl"></i><i class="kt-corner tr"></i><i class="kt-corner bl"></i><i class="kt-corner br"></i>
				<div class="kt-eyebrow">Planning drawdown</div>
				<div class="req-summary-title">{{ drawdown.lineCount }} source line{{ drawdown.lineCount === 1 ? "" : "s" }} · {{ drawdown.quantity }} Each</div>
				<p class="req-context-body">{{ money(drawdown.value) }}</p>
			</div>
			<div class="kt-card kt-blueprint req-card-pad-tight">
				<i class="kt-corner tl"></i><i class="kt-corner tr"></i><i class="kt-corner bl"></i><i class="kt-corner br"></i>
				<div class="kt-eyebrow">Technical requirements</div>
				<div class="req-summary-title">{{ confirmedTechnicalCount }} confirmed row{{ confirmedTechnicalCount === 1 ? "" : "s" }}</div>
			</div>
			<div class="kt-card kt-blueprint req-card-pad-tight">
				<i class="kt-corner tl"></i><i class="kt-corner tr"></i><i class="kt-corner bl"></i><i class="kt-corner br"></i>
				<div class="kt-eyebrow">Validation</div>
				<div class="req-summary-title" :class="validationReport.blocking_count ? 'req-validation-blocked' : 'req-validation-live'">
					{{ validationReport.blocking_count || 0 }} Blocking · {{ validationReport.warning_count || 0 }} Warning{{ (validationReport.warning_count || 0) === 1 ? "" : "s" }}
				</div>
			</div>
		</div>

		<table class="kt-table" data-testid="req-task-drawdown-table">
			<thead>
				<tr>
					<th>Contributing department</th>
					<th>Source requirement</th>
					<th class="req-num">Requested quantity</th>
					<th class="req-num">Requested value</th>
				</tr>
			</thead>
			<tbody>
				<tr v-for="(row, idx) in drawdownRows" :key="row.drawdown_line_id">
					<td>{{ row.organisation_unit_label }}</td>
					<td>{{ row.source_title }}</td>
					<td class="req-num">{{ requestedLines[idx] ? requestedLines[idx].requested_quantity : "" }} {{ row.unit }}</td>
					<td class="req-num">{{ money(requestedLines[idx] ? requestedLines[idx].requested_value : 0) }}</td>
				</tr>
			</tbody>
		</table>

		<table class="kt-table" data-testid="req-task-items-table">
			<thead>
				<tr>
					<th>Item</th>
					<th>Category</th>
					<th class="req-num">Quantity</th>
					<th>Intended use</th>
				</tr>
			</thead>
			<tbody>
				<tr v-for="item in items" :key="item.requisition_item_id">
					<td>{{ item.item_name }}</td>
					<td>{{ item.equipment_category }}</td>
					<td class="req-num">{{ item.quantity }} {{ item.unit }}</td>
					<td>{{ item.intended_use }}</td>
				</tr>
			</tbody>
		</table>

		<div class="kt-card-title">Technical requirements — {{ confirmedTechnicalCount }} confirmed rows</div>
		<table class="kt-table" data-testid="req-task-technical-table">
			<thead>
				<tr>
					<th>Characteristic</th>
					<th>Required value</th>
					<th>Status</th>
				</tr>
			</thead>
			<tbody>
				<tr v-for="row in confirmedTechnical" :key="row.technical_requirement_id">
					<td>{{ characteristicLabel(row.characteristic_key) }}</td>
					<td>{{ row.required_value_display }}</td>
					<td><span class="kt-status is-live">Confirmed</span></td>
				</tr>
			</tbody>
		</table>

		<p class="req-table-caption">Content digest — Generated by KenTender · <span class="req-digest">{{ (task.package || {}).content_digest }}</span></p>

		<div class="kt-card kt-blueprint req-card-pad">
			<i class="kt-corner tl"></i><i class="kt-corner tr"></i><i class="kt-corner bl"></i><i class="kt-corner br"></i>
			<p class="req-certification-statement">I confirm that this Requisition states the departments' operational need and minimum requirements and may be submitted to Procurement.</p>
		</div>
		<p class="req-table-caption">Decision by <strong>{{ actorName }}</strong>, {{ actorRoleLabel }} — certifying on behalf of {{ certifyingScope }}.</p>

		<div class="req-actions">
			<button type="button" class="kt-btn kt-btn-secondary" :disabled="pending || !task.can_act" data-testid="req-task-return" @click="$emit('return')">Return for correction</button>
			<button type="button" class="kt-btn kt-btn-primary" :disabled="pending || !task.can_act" data-testid="req-task-submit" @click="$emit('submit')">Submit to Procurement</button>
		</div>
	</div>
</template>

<script setup>
import { computed } from "vue";
import { formatMoney } from "../data/format.js";

const props = defineProps({
	task: { type: Object, required: true },
	actorName: { type: String, default: "" },
	actorRoleLabel: { type: String, default: "Head of User Department" },
	pending: Boolean,
});

defineEmits(["return", "submit"]);

const reference = computed(() => {
	const r = props.task.requisition || {};
	const v = props.task.version || {};
	return [r.requisition_reference, r.plan_item_id, v.version_number ? `Version ${v.version_number}` : ""].filter(Boolean).join(" · ");
});

const pkg = computed(() => props.task.package || {});
const items = computed(() => pkg.value.items || []);
const drawdownRows = computed(() => props.task.drawdown_context || []);
const requestedLines = computed(() => (props.task.version || {}).drawdown_lines || []);
const confirmedTechnical = computed(() => (pkg.value.technical_requirements || []).filter((r) => r.row_status === "Confirmed"));
const confirmedTechnicalCount = computed(() => confirmedTechnical.value.length);
const validationReport = computed(() => props.task.validation || {});

const drawdown = computed(() => {
	const lines = requestedLines.value;
	return {
		lineCount: lines.length,
		quantity: lines.reduce((sum, l) => sum + (l.requested_quantity || 0), 0),
		value: lines.reduce((sum, l) => sum + (l.requested_value || 0), 0),
	};
});

const certifyingScope = computed(() => {
	const count = new Set(drawdownRows.value.map((r) => r.organisation_unit)).size;
	return count > 1 ? "both contributing departments" : "the contributing department";
});

const catalogueByKey = computed(() => {
	const map = {};
	for (const c of (props.task.catalogue || {}).characteristics || []) map[c.key] = c;
	return map;
});
function characteristicLabel(key) {
	return (catalogueByKey.value[key] || {}).label || key;
}

function money(amount) {
	return formatMoney(amount);
}
</script>
