# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""BDS-CHG-001 v0.8 §5.12 (Account rows) and KT-STD-001 v1.8 §3B.7 (owner
decision 27 Sep 2026): every supplier-account state, read by every kind of
person, gives either a sound next step or no access — never a dead end, and
never an Account fact to someone outside the organisation. Writes
`docs/mvp-1-r1/12_bid_submission/evidence/v0_8/account_dead_end_matrix.md`."""

from __future__ import annotations

import os

import frappe

from kentender_core.services import next_step as ns

from kentender_suppliers.supplier_accounts.services import access, assignments, read
from kentender_suppliers.supplier_accounts.tests.support import AMINA, DAVID, MARY, PETER, STAFF, AccountsCase, key

READERS = (
	("Registrant (Mary Wanjiku)", MARY),
	("Supplier Representative (David Ouma)", DAVID),
	("Another supplier (Peter Mwangi)", PETER),
	("Supplier Account Support Officer (Amina Yusuf)", AMINA),
	("Internal staff (System Manager)", STAFF),
	("Technical reader (Administrator)", "Administrator"),
	("Signed-out visitor", "Guest"),
)
MATRIX = os.path.join(os.path.dirname(frappe.get_app_path("kentender_suppliers")), "..", "docs", "mvp-1-r1", "12_bid_submission", "evidence", "v0_8", "account_dead_end_matrix.md")


class TestAccountDeadEndMatrix(AccountsCase):
	rows: list[tuple[str, str, str, str, str]] = []

	@classmethod
	def tearDownClass(cls):
		if cls.rows:
			os.makedirs(os.path.dirname(MATRIX), exist_ok=True)
			with open(MATRIX, "w", encoding="utf-8") as out:
				out.write("# Supplier Account dead-end matrix — BDS-CHG-001 v0.8 §5.12 / KT-STD-001 v1.8 §3B.7\n\n")
				out.write("Generated by `supplier_accounts/tests/test_account_dead_end_matrix.py` (`make bds-dead-end-gate`). ")
				out.write("One row per Account state and reader of the Supplier Account read; a reader outside the organisation gets no access (Not found), never an Account fact. ")
				out.write("Internal people act on an Account from Desk (the support officer's My Work item and the Supplier Organisation form), not from this supplier read.\n\n")
				out.write("| State | Reader | Kind | Next step | Result |\n|---|---|---|---|---|\n")
				for state, reader, kind, headline, result in cls.rows:
					out.write(f"| {state} | {reader} | {kind} | {headline.replace('|', '/')} | {result} |\n")
		super().tearDownClass()

	def read_all(self, state, organisation, members):
		for label, user in READERS:
			try:
				view = read.get_supplier_account(organisation=organisation, user=user)
			except frappe.DoesNotExistError:
				self.assertNotIn(user, members, (state, label))
				self.rows.append((state, label, "—", "Not found", "No access (Not found)"))
				continue
			except frappe.ValidationError as error:
				self.assertEqual((user, getattr(error, "code", "")), ("Guest", "BDS_SIGN_IN_REQUIRED"), (state, label))
				self.rows.append((state, label, "—", "Sign in to start or continue a bid.", "No access (sign in)"))
				continue
			self.assertIn(user, members, (state, label))
			step = view["next_step"]
			self.assertEqual(ns.problems(step), [], (state, label, step))
			self.rows.append((state, label, step["label"] or step["kind"], step["headline"], "Sound"))

	def test_every_state_and_reader(self):
		fresh = read.get_supplier_account(user=PETER)
		self.assertEqual((fresh["state"], ns.problems(fresh["next_step"])), ("no_account", []))
		self.rows.append(("No account yet", "A signed-in person with no supplier account (Peter Mwangi)", fresh["next_step"]["label"], fresh["next_step"]["headline"], "Sound"))

		from kentender_suppliers.supplier_accounts.services import organisation as organisation_service, verification

		org = self.register()["organisation"]
		self.read_all("Pending verification", org, {MARY})
		# An older record without the official phone (registration now requires it)
		frappe.db.set_value("Supplier Organisation", org, "official_phone", "", update_modified=False)
		self.read_all("Official phone missing (older record)", org, {MARY})
		version = frappe.db.get_value("Supplier Organisation", org, "record_version")
		organisation_service.update_supplier_organisation(organisation=org, values={"official_phone": "+254 709 555 014"}, expected_version=version, idempotency_key=key(), user=MARY)
		verification.verify_account_communication(token=self.token(), user=MARY)
		assignments.assign_supplier_representative(organisation=org, email=DAVID, full_name="David Ouma", idempotency_key=key(), user=MARY)
		self.read_all("Active", org, {MARY, DAVID})
		version = frappe.db.get_value("Supplier Organisation", org, "record_version")
		access.suspend_supplier_account(organisation=org, reason="Reported misuse of the account.", expected_version=version, idempotency_key=key(), user=AMINA)
		self.read_all("Suspended", org, {MARY, DAVID})
