# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""KT-STD-001 v1.8 §3B.7 / PLN-CHG-001 v1.27 — the Planning dead-end matrix.

One plan is walked through every §5.7 state its lifecycle reaches (plus the
over-budget, waiting-on-budget and failed-publication states), and at each
state every responsibility able to read it reads the Annual Plan. For every
row the four §3B.7 rules are asserted:

1. the reader has an enabled action, or a next step naming a holder and a
   reason (`kentender_core.services.next_step.problems`);
2. every blocker carries a reason code and a fix (same helper);
3. every route fix opens a Planning (or System setup) page;
4. the next step's stage is the stage the tracker shows as current;
5. no reader is told to wait for themselves (found live 25 Sep 2026).

Plus §3B.6: a technical reader never gets Your turn except on the one named
exception (O4, publication recovery). The matrix is written to
`docs/mvp-1-r1/04_planning/evidence/v1_27/dead_end_matrix.md`.
"""

from __future__ import annotations

import os
from unittest.mock import patch

import frappe

from kentender_core.services import next_step as ns
from kentender_procurement.procurement_planning.errors import ProcurementPlanningError
from kentender_procurement.procurement_planning.services import (
	budget_revision,
	departmental_update,
	dpp_read,
	needs_intake,
	plan_finance,
	plan_governance,
	plan_read,
	plan_workbench,
	publication_pipeline,
)
from kentender_procurement.procurement_planning.tests import fixtures as fx
from kentender_procurement.procurement_planning.tests.test_plan_publication import PublicationCase, key

READERS = (
	("Procurement Planner", fx.PLANNER),
	("Departmental Author", fx.AUTHOR),
	("Head of Department", fx.HOD),
	("Finance Confirmation Officer", fx.FINANCE_OFFICER),
	("Budget Officer", fx.BUDGET_OFFICER),
	# one person holding two responsibilities (§6.1 permits combinations) —
	# found live 25 Sep 2026 told to wait for themselves
	("Finance Confirmation Officer and Budget Officer", fx.FINANCE_BUDGET),
	("Procurement Planner and Finance Confirmation Officer", fx.HYBRID_FINANCE),
	("Head of Procurement Function", fx.HOPF),
	("Accounting Officer", fx.ACCOUNTING_OFFICER),
	("Statutory approver", fx.STATUTORY),
	("Auditor", fx.AUDITOR),
	("Technical reader", "Administrator"),
	("Outsider", fx.OUTSIDER),
)
# Planning's own pages, System setup, and Budget (where a budget revision
# request is decided — BUD presents the Budget Officer's turn, §5.7).
ROUTES = {"annual-procurement-plan", "procurement-plan-item", "departmental-procurement-plan", "procurement-planning", "system-setup", "budget-funding"}
TURNS = (ns.KIND_YOUR_TURN, ns.KIND_BLOCKED)
# O4 — the one named exception to §3B.6.
TECHNICAL_TURN_STATES = {"Publication failed"}
MATRIX = os.path.join(
	os.path.dirname(frappe.get_app_path("kentender_procurement")), "..", "docs", "mvp-1-r1", "04_planning", "evidence", "v1_27", "dead_end_matrix.md",
)


class TestPlanningDeadEndMatrix(PublicationCase):
	rows: list[tuple[str, str, str, str, str]] = []

	@classmethod
	def tearDownClass(cls):
		if cls.rows:
			os.makedirs(os.path.dirname(MATRIX), exist_ok=True)
			with open(MATRIX, "w", encoding="utf-8") as out:
				out.write("# Planning dead-end matrix — PLN-CHG-001 v1.27 / KT-STD-001 v1.8 §3B.7\n\n")
				out.write("Generated by `procurement_planning/tests/test_dead_end_matrix.py` (`make planning-dead-end-gate`). ")
				out.write("One row per state and reader; a reader with no access to the record is listed as such.\n\n")
				out.write("| State | Reader | Kind | Next step | Result |\n|---|---|---|---|---|\n")
				for state, reader, kind, headline, result in cls.rows:
					out.write(f"| {state} | {reader} | {kind} | {headline.replace('|', '/')} | {result} |\n")
		super().tearDownClass()

	# ------------------------------------------------------------------

	def _read(self, fn, user):
		try:
			return fn(user)
		except (frappe.PermissionError, frappe.DoesNotExistError, ProcurementPlanningError):
			return None

	def check(self, state: str, fn) -> list[str]:
		failures = []
		for reader, user in READERS:
			view = self._read(fn, user)
			if view is None:
				self.rows.append((state, reader, "—", "cannot read this record", "pass"))
				continue
			step = view.get("next_step")
			journey = view.get("journey") or {}
			enabled = any(view.get(flag) for flag in ("can_request_funding", "can_sign_and_submit", "can_submit", "can_decide"))
			problems = ns.problems(step, has_enabled_action=enabled)
			for fix in (step or {}).get("fixes") or []:
				if fix.get("kind") == ns.FIX_ROUTE and (not fix.get("target") or fix["target"][0] not in ROUTES):
					problems.append(f"fix {fix.get('fix_id')} opens no Planning page")
			kind = (step or {}).get("kind", "")
			current = journey.get("current")
			if kind in (*TURNS, ns.KIND_WAITING) and current and step.get("stage") and step["stage"] != current:
				problems.append(f"stage {step['stage']} is not the tracker's {current}")
			if kind == ns.KIND_WAITING and frappe.db.get_value("User", user, "full_name") in ((step.get("holder") or {}).get("people") or []):
				problems.append("the reader is told to wait for themselves")
			if user == "Administrator" and kind in TURNS and state not in TECHNICAL_TURN_STATES:
				problems.append("a technical reader was given a turn")
			result = "pass" if not problems else "FAIL: " + "; ".join(problems)
			if problems:
				failures.append(f"{state} / {reader}: {'; '.join(problems)}")
			self.rows.append((state, reader, kind or "none", (step or {}).get("headline") or "—", result))
		return failures

	def plan(self, reference):
		return lambda user: plan_read.get_annual_plan(plan_reference=reference, user=user)

	# ------------------------------------------------------------------

	def test_every_annual_plan_state_leaves_every_reader_somewhere_to_go(self):
		failures = []
		accepted, entries, dpp = self._accept_direct([{"indicative_amount": 1_000_000}])
		reference = accepted["annual_plan"]
		dpp_view = lambda user: dpp_read.get_departmental_plan(dpp_reference=frappe.db.get_value("Departmental Plan", dpp, "dpp_reference"), user=user)  # noqa: E731
		failures += self.check("Departmental plan accepted", dpp_view)
		# Owner decision 26 Sep 2026 — a Need accepted after the plan was: the
		# plan is not finished, and the §3B.7 rules alone cannot see that (a
		# "Done" answer passes them), so the department's turn is asserted too.
		with patch.object(needs_intake, "current_accepted_sources", return_value=[fx.accepted_source()]):
			failures += self.check("Departmental plan accepted — a need accepted after it", dpp_view)
			for reader, user in (("Departmental Author", fx.AUTHOR), ("Head of Department", fx.HOD)):
				step = dpp_view(user)["next_step"]
				if step["kind"] != ns.KIND_YOUR_TURN or step["primary_action"] != "create_update":
					failures.append(f"Departmental plan accepted — a need accepted after it / {reader}: {step['kind']} ({step['headline']}), not Create update")
		failures += self.check("Draft — requirement not yet in a purchase", self.plan(reference))

		frappe.set_user(fx.PLANNER)
		view = plan_read.get_annual_plan(plan_reference=reference)
		formed = plan_workbench.form_plan_items(
			plan_version=accepted["annual_plan_version"], dpp_entries=entries, mode="each",
			expected_record_version=view["record_version"], idempotency_key=key(),
		)
		item_id = formed["created_items"][0]
		failures += self.check("Draft — purchase incomplete", self.plan(reference))
		self.complete(item_id, procurement_method="")
		failures += self.check("Draft — purchase needs a procurement method", self.plan(reference))
		self.complete(item_id)
		failures += self.check("Draft — ready to send to Finance", self.plan(reference))

		# over the line's approved amount (fixture-only override), then the
		# Budget Officer asked to revise it
		allocations = frappe.get_all("Plan Source Allocation", filters={"plan_version": accepted["annual_plan_version"]}, pluck="name")
		for name in allocations:
			frappe.db.set_value("Plan Source Allocation", name, "indicative_amount", 150_000_000, update_modified=False)
		failures += self.check("Draft — over budget", self.plan(reference))
		# owner decision 26 Sep 2026 — the departmental correction route
		frappe.set_user(fx.PLANNER)
		view = plan_read.get_annual_plan(plan_reference=reference)
		departmental_update.request_departmental_plan_update(
			plan_version=view["version_reference"], budget_line=fx.BUDGET_LINE, organisation_unit=fx.OU_ALPHA,
			expected_record_version=view["record_version"], idempotency_key=key(),
		)
		failures += self.check("Draft — waiting for a departmental plan update", self.plan(reference))
		dpp_reference = frappe.db.get_value("Departmental Plan", dpp, "dpp_reference")
		failures += self.check("Departmental plan — update requested", lambda user: dpp_read.get_departmental_plan(dpp_reference=dpp_reference, user=user))
		frappe.set_user(fx.PLANNER)
		view = plan_read.get_annual_plan(plan_reference=reference)
		budget_revision.request_budget_revision(
			plan_version=view["version_reference"], budget_line=fx.BUDGET_LINE,
			expected_record_version=view["record_version"], idempotency_key=key(),
		)
		failures += self.check("Draft — waiting for a budget revision", self.plan(reference))
		for name in allocations:
			frappe.db.set_value("Plan Source Allocation", name, "indicative_amount", 1_000_000, update_modified=False)
		failures += self.check("Draft — fits again, request still open", self.plan(reference))

		frappe.set_user(fx.PLANNER)
		view = plan_read.get_annual_plan(plan_reference=reference)
		requested = plan_finance.request_plan_funding_confirmation(
			plan_version=view["version_reference"], expected_record_version=view["record_version"], idempotency_key=key(),
		)
		failures += self.check("Awaiting funding confirmation", self.plan(reference))
		task = frappe.get_doc("Plan Finance Task", requested["task"])
		failures += self.check("Finance review task", lambda user: plan_read.get_finance_task(task=task.name, user=user))
		frappe.set_user(fx.FINANCE_OFFICER)
		plan_finance.confirm_plan_funding(task=task.name, task_token=task.task_token, idempotency_key=key())
		failures += self.check("Funding confirmed — signature", self.plan(reference))

		frappe.set_user(fx.PLANNER)
		view = plan_read.get_annual_plan(plan_reference=reference)
		frappe.set_user(fx.HOPF)
		submitted = plan_governance.submit_consolidated_plan(
			plan_version=view["version_reference"], expected_record_version=view["record_version"], idempotency_key=key(),
		)
		failures += self.check("Awaiting Accounting Officer", self.plan(reference))
		failures += self.check("AO review task", lambda user: plan_read.get_plan_governance_task(task=submitted["task"], user=user))
		ao_task = frappe.get_doc("Plan Governance Task", submitted["task"])
		frappe.set_user(fx.ACCOUNTING_OFFICER)
		adopted = plan_governance.adopt_and_submit_plan(task=ao_task.name, task_token=ao_task.task_token, idempotency_key=key())
		failures += self.check("Awaiting statutory approval", self.plan(reference))
		statutory_task = frappe.get_doc("Plan Governance Task", adopted["statutory_task"])
		frappe.set_user(fx.STATUTORY)
		approved = plan_governance.approve_annual_plan(task=statutory_task.name, task_token=statutory_task.task_token, idempotency_key=key())
		failures += self.check("Approved — Treasury submission needed", self.plan(reference))
		publication = approved["publication"]
		failures += self.check("Publication task — Treasury", lambda user: plan_read.get_publication_task(publication=publication, user=user))

		version = frappe.db.get_value("Plan Publication", publication, "plan_version")
		self.record_treasury(version)
		destination = frappe.get_doc("Plan Publication", publication).destination
		frappe.db.set_value("Annual Plan Publication Destination", destination, "sandbox_outcome", "Fail")
		frappe.set_user("Administrator")
		publication_pipeline.publish_annual_plan(plan_version=version, idempotency_key=key())
		failures += self.check("Publication failed", lambda user: plan_read.get_publication_task(publication=publication, user=user))

		frappe.db.set_value("Annual Plan Publication Destination", destination, "sandbox_outcome", "Acknowledge")
		frappe.set_user("Administrator")
		publication_pipeline.retry_publication(publication=publication, idempotency_key=key())
		failures += self.check("In force", self.plan(reference))

		self.assertEqual(failures, [], "\n".join(failures))
