# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""Central denial code catalogue — SEC-0200 / Cursor pack §7 + std engine + doc 9 §7.5.

Stable ``denial_code`` strings for authorization, release, completion, publication,
downstream controls, and **Tender Management v2** (doc 9 §7.5). Use :class:`DenialCode`
or :func:`build_denial` instead of ad-hoc literals in core services.

- Pack §7 lists **35** std-engine / workstream-7 codes.
- Doc 9 §7.5 lists **37** TM2 denial strings (exact spellings for UI / smoke doc 8).
- :class:`DenialCode` also includes ``PUBLISH_CONFIGURATION_SNAPSHOT_MISSING`` and
  ``AUDIT_EXPORT_DENIED`` (implementation extensions).
"""

from __future__ import annotations

from enum import StrEnum
from typing import Literal, TypedDict

# --- Exact pack §7 catalogue (for regression / doc parity) --------------------
PACK_SEC_0200_CODES: frozenset[str] = frozenset(
	{
		# Authorization
		"STD_AUTH_PERMISSION_DENIED",
		"STD_AUTH_ROLE_SCOPE_DENIED",
		"STD_AUTH_OBJECT_SCOPE_DENIED",
		"STD_AUTH_TENDER_CONTEXT_REQUIRED",
		"STD_AUTH_ACTIVE_VERSION_LOCKED",
		"STD_AUTH_ADDENDUM_REQUIRED",
		"STD_AUTH_OUTPUT_LOCKED",
		"STD_AUTH_MANUAL_CRITERIA_DENIED",
		"STD_AUTH_DCM_CONTRACT_BINDING_VIOLATION",
		# Release
		"RELEASE_PERMISSION_DENIED",
		"PACKAGE_ALREADY_RELEASED",
		"PLAN_PACKAGE_NOT_APPROVED",
		"PLAN_BUDGET_NOT_CONFIRMED",
		"STD_NO_ELIGIBLE_TEMPLATE",
		"STD_MULTIPLE_ELIGIBLE_REQUIRES_SELECTION",
		# Completion
		"WORKS_INSTANCE_LOCKED",
		"WORKS_CATEGORY_INVALID",
		"WORKS_MANUAL_EVALUATION_CRITERIA_DENIED",
		"BOQ_SUPPLIER_RATE_ENTRY_DENIED",
		"BOQ_ARITHMETIC_CORRECTION_STAGE_VIOLATION",
		# Publication
		"PUBLISH_PERMISSION_DENIED",
		"PUBLISH_APPROVAL_REQUIRED",
		"PUBLISH_READINESS_NOT_READY",
		"PUBLISH_OUTPUT_STALE",
		"PUBLISH_OUTPUT_MISSING",
		"PUBLISH_EVIDENCE_PACKAGE_FAILED",
		"POST_PUBLICATION_EDIT_DENIED_ADDENDUM_REQUIRED",
		# Downstream
		"OUTPUT_TYPE_INVALID_FOR_CONSUMER",
		"OUTPUT_STALE",
		"OUTPUT_SUPERSEDED",
		"OUTPUT_NOT_LINKED_TO_SNAPSHOT",
		"MANUAL_SUBMISSION_REQUIREMENT_DENIED",
		"MANUAL_OPENING_EVALUATION_FIELD_DENIED",
		"MANUAL_EVALUATION_CRITERIA_DENIED",
		"CONTRACT_BINDING_VIOLATION",
	},
)

# Stable titles used by PUB-0400 alongside pack publication codes (not in pack §7 list).
EXTENSION_DENIAL_CODES: frozenset[str] = frozenset(
	{"PUBLISH_CONFIGURATION_SNAPSHOT_MISSING", "AUDIT_EXPORT_DENIED"}
)

# Doc 9 §7.5 — Tender Management v2 (exact strings; doc 8 smoke references these).
PACK_TM2_DOC9_SECTION_75_DENIAL_CODES: frozenset[str] = frozenset(
	{
		"AUTH_ROLE_DENIED",
		"AUTH_STATE_DENIED",
		"AUTH_CONTEXT_DENIED",
		"AUTH_SOD_DENIED",
		"AUTH_DEADLINE_PASSED",
		"AUTH_STD_NOT_READY",
		"AUTH_STD_MODEL_MISSING",
		"AUTH_BUNDLE_MISSING_OR_STALE",
		"AUTH_DSM_MISSING_OR_STALE",
		"AUTH_DOM_MISSING_OR_STALE",
		"AUTH_DEM_MISSING_OR_STALE",
		"AUTH_DCM_MISSING_OR_STALE",
		"AUTH_PUBLICATION_SNAPSHOT_MISSING",
		"AUTH_SUPPLIER_INELIGIBLE",
		"AUTH_INVITATION_REQUIRED",
		"AUTH_ADDENDUM_ACK_REQUIRED",
		"AUTH_SEALED_BID_DENIED",
		"AUTH_LOCKED_RECORD",
		"AUTH_REASON_REQUIRED",
		"AUTH_OVERRIDE_NOT_ALLOWED",
		"AUTH_LEGACY_PATH_DENIED",
		"AUTH_ACTION_AVAILABILITY_DENIED",
		"AUTH_LOGIN_REQUIRED",
		"AUTH_CONTRACT_PRICE_SOURCE_INVALID",
		"PACKAGE_NOT_AUTHORIZED",
		"ACTIVE_TENDER_EXISTS",
		"STD_TEMPLATE_NOT_ACTIVE",
		"STD_TEMPLATE_INCOMPATIBLE",
		"ADDENDUM_IMPACT_ANALYSIS_REQUIRED",
		"BOQ_QUANTITY_LOCKED",
		"BOQ_FIXED_AMOUNT_LOCKED",
		"REQUIRED_BOQ_RATE_MISSING",
		"INVALID_BOQ_RATE_NEGATIVE",
		"DEADLINE_NOT_REACHED",
		"OPENING_NOT_COMPLETED",
		"AWARD_DECISION_MISSING",
	}
)

_EXPECTED_TM2_75_COUNT = 36


class DenialCode(StrEnum):
	"""Stable ``denial_code`` / ``frappe.throw`` title values (std pack + TM2 §7.5 + extensions)."""

	# --- Authorization (std pack §7) ----------------------------------------
	STD_AUTH_PERMISSION_DENIED = "STD_AUTH_PERMISSION_DENIED"
	STD_AUTH_ROLE_SCOPE_DENIED = "STD_AUTH_ROLE_SCOPE_DENIED"
	STD_AUTH_OBJECT_SCOPE_DENIED = "STD_AUTH_OBJECT_SCOPE_DENIED"
	STD_AUTH_TENDER_CONTEXT_REQUIRED = "STD_AUTH_TENDER_CONTEXT_REQUIRED"
	STD_AUTH_ACTIVE_VERSION_LOCKED = "STD_AUTH_ACTIVE_VERSION_LOCKED"
	STD_AUTH_ADDENDUM_REQUIRED = "STD_AUTH_ADDENDUM_REQUIRED"
	STD_AUTH_OUTPUT_LOCKED = "STD_AUTH_OUTPUT_LOCKED"
	STD_AUTH_MANUAL_CRITERIA_DENIED = "STD_AUTH_MANUAL_CRITERIA_DENIED"
	STD_AUTH_DCM_CONTRACT_BINDING_VIOLATION = "STD_AUTH_DCM_CONTRACT_BINDING_VIOLATION"
	# --- Release ------------------------------------------------------------
	RELEASE_PERMISSION_DENIED = "RELEASE_PERMISSION_DENIED"
	PACKAGE_ALREADY_RELEASED = "PACKAGE_ALREADY_RELEASED"
	PLAN_PACKAGE_NOT_APPROVED = "PLAN_PACKAGE_NOT_APPROVED"
	PLAN_BUDGET_NOT_CONFIRMED = "PLAN_BUDGET_NOT_CONFIRMED"
	STD_NO_ELIGIBLE_TEMPLATE = "STD_NO_ELIGIBLE_TEMPLATE"
	STD_MULTIPLE_ELIGIBLE_REQUIRES_SELECTION = "STD_MULTIPLE_ELIGIBLE_REQUIRES_SELECTION"
	# --- Completion ---------------------------------------------------------
	WORKS_INSTANCE_LOCKED = "WORKS_INSTANCE_LOCKED"
	WORKS_CATEGORY_INVALID = "WORKS_CATEGORY_INVALID"
	WORKS_MANUAL_EVALUATION_CRITERIA_DENIED = "WORKS_MANUAL_EVALUATION_CRITERIA_DENIED"
	BOQ_SUPPLIER_RATE_ENTRY_DENIED = "BOQ_SUPPLIER_RATE_ENTRY_DENIED"
	BOQ_ARITHMETIC_CORRECTION_STAGE_VIOLATION = "BOQ_ARITHMETIC_CORRECTION_STAGE_VIOLATION"
	# --- Publication --------------------------------------------------------
	PUBLISH_PERMISSION_DENIED = "PUBLISH_PERMISSION_DENIED"
	PUBLISH_APPROVAL_REQUIRED = "PUBLISH_APPROVAL_REQUIRED"
	PUBLISH_READINESS_NOT_READY = "PUBLISH_READINESS_NOT_READY"
	PUBLISH_OUTPUT_STALE = "PUBLISH_OUTPUT_STALE"
	PUBLISH_OUTPUT_MISSING = "PUBLISH_OUTPUT_MISSING"
	PUBLISH_EVIDENCE_PACKAGE_FAILED = "PUBLISH_EVIDENCE_PACKAGE_FAILED"
	POST_PUBLICATION_EDIT_DENIED_ADDENDUM_REQUIRED = "POST_PUBLICATION_EDIT_DENIED_ADDENDUM_REQUIRED"
	# --- Downstream ---------------------------------------------------------
	OUTPUT_TYPE_INVALID_FOR_CONSUMER = "OUTPUT_TYPE_INVALID_FOR_CONSUMER"
	OUTPUT_STALE = "OUTPUT_STALE"
	OUTPUT_SUPERSEDED = "OUTPUT_SUPERSEDED"
	OUTPUT_NOT_LINKED_TO_SNAPSHOT = "OUTPUT_NOT_LINKED_TO_SNAPSHOT"
	MANUAL_SUBMISSION_REQUIREMENT_DENIED = "MANUAL_SUBMISSION_REQUIREMENT_DENIED"
	MANUAL_OPENING_EVALUATION_FIELD_DENIED = "MANUAL_OPENING_EVALUATION_FIELD_DENIED"
	MANUAL_EVALUATION_CRITERIA_DENIED = "MANUAL_EVALUATION_CRITERIA_DENIED"
	CONTRACT_BINDING_VIOLATION = "CONTRACT_BINDING_VIOLATION"
	# --- Doc 9 §7.5 — Tender Management v2 ----------------------------------
	AUTH_ACTION_AVAILABILITY_DENIED = "AUTH_ACTION_AVAILABILITY_DENIED"
	AUTH_ADDENDUM_ACK_REQUIRED = "AUTH_ADDENDUM_ACK_REQUIRED"
	AUTH_BUNDLE_MISSING_OR_STALE = "AUTH_BUNDLE_MISSING_OR_STALE"
	AUTH_CONTEXT_DENIED = "AUTH_CONTEXT_DENIED"
	AUTH_CONTRACT_PRICE_SOURCE_INVALID = "AUTH_CONTRACT_PRICE_SOURCE_INVALID"
	AUTH_DCM_MISSING_OR_STALE = "AUTH_DCM_MISSING_OR_STALE"
	AUTH_DEADLINE_PASSED = "AUTH_DEADLINE_PASSED"
	AUTH_DEM_MISSING_OR_STALE = "AUTH_DEM_MISSING_OR_STALE"
	AUTH_DOM_MISSING_OR_STALE = "AUTH_DOM_MISSING_OR_STALE"
	AUTH_DSM_MISSING_OR_STALE = "AUTH_DSM_MISSING_OR_STALE"
	AUTH_INVITATION_REQUIRED = "AUTH_INVITATION_REQUIRED"
	AUTH_LEGACY_PATH_DENIED = "AUTH_LEGACY_PATH_DENIED"
	AUTH_LOCKED_RECORD = "AUTH_LOCKED_RECORD"
	AUTH_LOGIN_REQUIRED = "AUTH_LOGIN_REQUIRED"
	AUTH_OVERRIDE_NOT_ALLOWED = "AUTH_OVERRIDE_NOT_ALLOWED"
	AUTH_PUBLICATION_SNAPSHOT_MISSING = "AUTH_PUBLICATION_SNAPSHOT_MISSING"
	AUTH_REASON_REQUIRED = "AUTH_REASON_REQUIRED"
	AUTH_ROLE_DENIED = "AUTH_ROLE_DENIED"
	AUTH_SEALED_BID_DENIED = "AUTH_SEALED_BID_DENIED"
	AUTH_SOD_DENIED = "AUTH_SOD_DENIED"
	AUTH_STATE_DENIED = "AUTH_STATE_DENIED"
	AUTH_STD_MODEL_MISSING = "AUTH_STD_MODEL_MISSING"
	AUTH_STD_NOT_READY = "AUTH_STD_NOT_READY"
	AUTH_SUPPLIER_INELIGIBLE = "AUTH_SUPPLIER_INELIGIBLE"
	ACTIVE_TENDER_EXISTS = "ACTIVE_TENDER_EXISTS"
	ADDENDUM_IMPACT_ANALYSIS_REQUIRED = "ADDENDUM_IMPACT_ANALYSIS_REQUIRED"
	AWARD_DECISION_MISSING = "AWARD_DECISION_MISSING"
	BOQ_FIXED_AMOUNT_LOCKED = "BOQ_FIXED_AMOUNT_LOCKED"
	BOQ_QUANTITY_LOCKED = "BOQ_QUANTITY_LOCKED"
	DEADLINE_NOT_REACHED = "DEADLINE_NOT_REACHED"
	INVALID_BOQ_RATE_NEGATIVE = "INVALID_BOQ_RATE_NEGATIVE"
	OPENING_NOT_COMPLETED = "OPENING_NOT_COMPLETED"
	PACKAGE_NOT_AUTHORIZED = "PACKAGE_NOT_AUTHORIZED"
	REQUIRED_BOQ_RATE_MISSING = "REQUIRED_BOQ_RATE_MISSING"
	STD_TEMPLATE_INCOMPATIBLE = "STD_TEMPLATE_INCOMPATIBLE"
	STD_TEMPLATE_NOT_ACTIVE = "STD_TEMPLATE_NOT_ACTIVE"
	# --- Implementation extension (PUB-0400 / audit) -----------------------
	PUBLISH_CONFIGURATION_SNAPSHOT_MISSING = "PUBLISH_CONFIGURATION_SNAPSHOT_MISSING"
	AUDIT_EXPORT_DENIED = "AUDIT_EXPORT_DENIED"


RiskLevel = Literal["Low", "Medium", "High", "Critical"]


class StandardDenialPayload(TypedDict):
	"""Pack §7 JSON shape for API / action-availability responses."""

	allowed: Literal[False]
	denial_code: str
	message: str
	risk_level: str


def all_denial_code_values() -> frozenset[str]:
	"""Every :class:`DenialCode` string value (std pack + TM2 §7.5 + extensions)."""
	return frozenset(m.value for m in DenialCode)


def assert_pack_coverage() -> None:
	"""``PACK_SEC_0200_CODES`` ⊆ enum values; extensions disjoint from pack."""
	values = all_denial_code_values()
	if not PACK_SEC_0200_CODES <= values:
		missing = PACK_SEC_0200_CODES - values
		raise AssertionError(f"SEC-0200 pack codes missing from DenialCode: {missing!r}")
	if PACK_SEC_0200_CODES & EXTENSION_DENIAL_CODES:
		raise AssertionError("Pack and extension denial sets must not overlap")
	if not EXTENSION_DENIAL_CODES <= values:
		missing = EXTENSION_DENIAL_CODES - values
		raise AssertionError(f"Extension denial codes missing from DenialCode: {missing!r}")


def assert_tm2_doc9_section_75_coverage() -> None:
	"""Doc 9 §7.5 codes ⊆ :class:`DenialCode`; disjoint from std pack and extensions."""
	values = all_denial_code_values()
	if len(PACK_TM2_DOC9_SECTION_75_DENIAL_CODES) != _EXPECTED_TM2_75_COUNT:
		raise AssertionError(
			f"PACK_TM2_DOC9_SECTION_75_DENIAL_CODES must have {_EXPECTED_TM2_75_COUNT} entries "
			f"(got {len(PACK_TM2_DOC9_SECTION_75_DENIAL_CODES)})."
		)
	if not PACK_TM2_DOC9_SECTION_75_DENIAL_CODES <= values:
		missing = PACK_TM2_DOC9_SECTION_75_DENIAL_CODES - values
		raise AssertionError(f"Doc 9 §7.5 codes missing from DenialCode: {sorted(missing)!r}")
	if PACK_TM2_DOC9_SECTION_75_DENIAL_CODES & PACK_SEC_0200_CODES:
		overlap = PACK_TM2_DOC9_SECTION_75_DENIAL_CODES & PACK_SEC_0200_CODES
		raise AssertionError(f"TM2 §7.5 overlaps std pack §7: {overlap!r}")
	if PACK_TM2_DOC9_SECTION_75_DENIAL_CODES & EXTENSION_DENIAL_CODES:
		overlap = PACK_TM2_DOC9_SECTION_75_DENIAL_CODES & EXTENSION_DENIAL_CODES
		raise AssertionError(f"TM2 §7.5 overlaps extension set: {overlap!r}")


assert_pack_coverage()
assert_tm2_doc9_section_75_coverage()


def is_known_denial_code(value: str) -> bool:
	return (value or "").strip() in all_denial_code_values()


def build_denial(
	denial_code: DenialCode | str,
	*,
	message: str,
	risk_level: RiskLevel = "High",
) -> StandardDenialPayload:
	"""Build the pack §7 denial object (``allowed: false``)."""
	code = denial_code.value if isinstance(denial_code, DenialCode) else str(denial_code)
	if not is_known_denial_code(code):
		raise ValueError(f"Unknown denial_code: {code!r}")
	return {
		"allowed": False,
		"denial_code": code,
		"message": (message or "").strip(),
		"risk_level": risk_level,
	}
