# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""BDS-CHG-001 v0.8 §5.12 and KT-STD-001 v1.8 §3B.7 (plan Phase 10,
BDS8-1002): every bid state, read by every kind of person, gives either a
sound next step (an action, or a named holder and a reason) or no access at
all — never a dead end, and never a supplier fact to someone outside the
bid's organisation. Writes
`docs/mvp-1-r1/12_bid_submission/evidence/v0_8/dead_end_matrix.md`."""

from __future__ import annotations

import os
from unittest import mock

import frappe

from kentender_core.services import next_step as ns

from kentender_procurement.bid_submission import api
from kentender_procurement.bid_submission.services import errors, reads, save, simulation, start_bid, submission
from kentender_procurement.bid_submission.test_services import trust
from kentender_procurement.bid_submission.tests.support import AFYA, DAVID, GRACE, KISIWA, MARY, PETER, fill_everything, key
from kentender_procurement.bid_submission.tests.test_guidance import DANIEL, NADIA, GuidanceCase
from kentender_procurement.tenders.tests import fixtures as tender_fx

READERS = (
	("Supplier Representative (David Ouma)", DAVID),
	("Authorised Signatory (Mary Wanjiku)", MARY),
	("Another supplier (Peter Mwangi)", PETER),
	("Signed-out visitor", "Guest"),
	("Head of Procurement Function", tender_fx.HOPF),
	("Procurement Officer", tender_fx.OFFICER),
	("Technical Operator (Daniel Otieno)", DANIEL),
	("Release Operator (Nadia Kamau)", NADIA),
	("Technical reader (Administrator)", "Administrator"),
)
MATRIX = os.path.join(os.path.dirname(frappe.get_app_path("kentender_procurement")), "..", "docs", "mvp-1-r1", "12_bid_submission", "evidence", "v0_8", "dead_end_matrix.md")
OWNERS = {DAVID, MARY}


class TestBidDeadEndMatrix(GuidanceCase):
	rows: list[tuple[str, str, str, str, str]] = []

	@classmethod
	def tearDownClass(cls):
		if cls.rows:
			os.makedirs(os.path.dirname(MATRIX), exist_ok=True)
			with open(MATRIX, "w", encoding="utf-8") as out:
				out.write("# Bid Submission dead-end matrix — BDS-CHG-001 v0.8 §5.12 / KT-STD-001 v1.8 §3B.7\n\n")
				out.write("Generated by `bid_submission/tests/test_dead_end_matrix.py` (`make bds-dead-end-gate`) on a test world with the production switch on and the simulated services. ")
				out.write("One row per bid state and reader of the bid workspace; a reader outside the bid's organisation gets no access (Not found), never a bid fact.\n\n")
				out.write("| State | Reader | Kind | Next step | Result |\n|---|---|---|---|---|\n")
				for state, reader, kind, headline, result in cls.rows:
					out.write(f"| {state} | {reader} | {kind} | {headline.replace('|', '/')} | {result} |\n")
		super().tearDownClass()

	def read_all(self, state, bid=None, readers=READERS, owners=OWNERS):
		for label, user in readers:
			frappe.set_user(user)
			try:
				view = api.get_bid_workspace(bid_reference=bid or self.bid)
			except errors.BidSubmissionError as error:
				self.assertEqual(error.code, "BDS_SIGN_IN_REQUIRED", (state, label))
				self.rows.append((state, label, "—", "Sign in to start or continue a bid.", "No access (sign in)"))
				continue
			finally:
				frappe.set_user("Administrator")
			if view.get("outcome") == "NOT_FOUND":
				self.assertNotIn(user, owners, (state, label))
				self.rows.append((state, label, "—", "Bid not found", "No access (Not found)"))
				continue
			step = view["next_step"]
			self.assertEqual(ns.problems(step), [], (state, label, step))
			self.rows.append((state, label, step["label"] or step["kind"], step["headline"], "Sound"))

	def blank_answer(self, value=None):
		field = next(f for g in reads.get_bid_task(bid_reference=self.bid, task="requirements", user=DAVID)["groups"] for f in g["fields"] if f["label"] == "Offered make and model")
		self.assertTrue(save.save_bid_task(bid_reference=self.bid, task="requirements", values={field["handle"]: value}, expected_record_version=self.version(), idempotency_key=key(), user=DAVID)["ok"])

	def test_every_state_and_reader(self):
		self.blank_answer(None)
		self.read_all("Draft in progress")
		self.blank_answer("ApexBook Pro 14")
		self.read_all("Ready to submit")
		trust.revoke_certificate(self.certificate)
		self.read_all("Signatory certificate required")
		self.certificate = trust.issue_certificate(user=MARY, organisation=AFYA, subject_name="Mary Wanjiku", valid_from="2027-01-01 00:00:00", valid_to="2027-12-31 23:59:59")
		for state, controls in (("Production gate closed", {"gate_closed": 1}), ("Signing service down", {"trust_service_down": 1}), ("Submission service down", {"custody_service_down": 1})):
			simulation.set_controls(**controls)
			self.read_all(state)
			simulation.reset_controls()
		with mock.patch("kentender_core.services.public_portal.get_public_portal_information", return_value={"status": "Incomplete"}):
			self.read_all("Supplier portal information incomplete")
		simulation.set_controls(deposit_outcome="Reject", rejection_reference="TBX-REJECT-033-01")
		self.submit(self.signed())
		self.read_all("Tender box rejected the attempt")
		simulation.set_controls(deposit_outcome="Uncertain")
		self.submit(self.signed())
		self.read_all("Submission unconfirmed")
		simulation.set_controls(uncertain_resolution="Accept")
		submission.reconcile_uncertain_attempts()
		simulation.reset_controls()
		self.read_all("Submitted, before the deadline")
		self.at("2027-05-31 08:30:00")
		self.replace()
		self.read_all("Replacement Draft")
		self.at("2027-05-31 09:00:00")
		self.withdraw()
		self.read_all("Withdrawn, before the deadline")
		self.at("2027-05-31 09:30:00")
		self.replace()
		self.read_all("Started again after a withdrawal")
		# a second supplier submits, to read a submitted bid after the deadline
		other = start_bid.start_bid(tender_reference=self.reference, organisation=KISIWA, arrangement=self.single(), notice_contact_id=f"{KISIWA}-C1", idempotency_key=key(), user=PETER)["bid_reference"]
		fill_everything(other, user=PETER)
		trust.issue_certificate(user=GRACE, organisation=KISIWA, subject_name="Grace Njeri", valid_from="2027-01-01 00:00:00", valid_to="2027-12-31 23:59:59")
		self.at("2027-05-31 10:00:00")
		from kentender_procurement.bid_submission.services import signature

		version = frappe.db.get_value("Bid Workspace", other, "record_version")
		request = signature.prepare_bid_signature(bid_reference=other, confirmed=True, expected_record_version=version, idempotency_key=key(), user=GRACE)
		signed = signature.sign_with_test_trust_service(signing_request=request["signing_request"], user=GRACE)["signature"]
		self.assertTrue(submission.submit_bid(bid_reference=other, signature_ref=signed, confirmed=True, expected_record_version=version, idempotency_key=key(), user=GRACE)["ok"])
		kisiwa = (("Supplier Representative (Peter Mwangi)", PETER), ("Authorised Signatory (Grace Njeri)", GRACE), ("Another supplier (David Ouma)", DAVID))
		self.at(str(self.deadline()))
		self.read_all("Draft not submitted, after the deadline")
		self.read_all("Submitted, after the deadline", bid=other, readers=kisiwa, owners={PETER, GRACE})
