# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""Domain event identifiers and payload conventions (JSON-serializable) for STD Instance flows.

Complements ``audit`` (STDINST-1100).
"""

from __future__ import annotations

EVT_STDINST_CREATED = "STD_INSTANCE_CREATED"
EVT_STDINST_PARAMETER_CHANGED = "STD_PARAMETER_CHANGED"
EVT_STDINST_WORKS_REQUIREMENT_CHANGED = "STD_WORKS_REQUIREMENT_CHANGED"
EVT_STDINST_DRAWING_REGISTER_CHANGED = "STD_DRAWING_REGISTER_CHANGED"
EVT_STDINST_ATTACHMENT_CHANGED = "STD_ATTACHMENT_CHANGED"
EVT_STDINST_BOQ_CHANGED = "STD_BOQ_CHANGED"
EVT_STDINST_OUTPUTS_STALED = "STD_OUTPUTS_STALED"
EVT_STDINST_OUTPUT_GENERATED = "STD_OUTPUT_GENERATED"
EVT_STDINST_OUTPUT_GENERATION_FAILED = "STD_OUTPUT_GENERATION_FAILED"
EVT_STDINST_READINESS_EVALUATED = "STD_READINESS_EVALUATED"
EVT_STDINST_SNAPSHOT_CREATED = "STD_SNAPSHOT_CREATED"
EVT_STDINST_PUBLICATION_LOCK_APPLIED = "STD_PUBLICATION_LOCK_APPLIED"
EVT_STDINST_ADDENDUM_IMPACT_ANALYSED = "STD_ADDENDUM_IMPACT_ANALYSED"
EVT_STDINST_OUTPUTS_SUPERSEDED = "STD_OUTPUTS_SUPERSEDED"
EVT_STDINST_DENIED_EDIT_ATTEMPT = "STD_DENIED_EDIT_ATTEMPT"
EVT_STDINST_DENIED_DOWNSTREAM_RULE_INJECTION = "STD_DENIED_DOWNSTREAM_RULE_INJECTION"

EVENT_ACTIONS: dict[str, str] = {
	EVT_STDINST_CREATED: "create_instance",
	EVT_STDINST_PARAMETER_CHANGED: "change_parameter",
	EVT_STDINST_WORKS_REQUIREMENT_CHANGED: "change_works_requirement",
	EVT_STDINST_DRAWING_REGISTER_CHANGED: "change_drawing_register",
	EVT_STDINST_ATTACHMENT_CHANGED: "change_attachment",
	EVT_STDINST_BOQ_CHANGED: "change_boq",
	EVT_STDINST_OUTPUTS_STALED: "stale_outputs",
	EVT_STDINST_OUTPUT_GENERATED: "generate_output",
	EVT_STDINST_OUTPUT_GENERATION_FAILED: "generate_output_failed",
	EVT_STDINST_READINESS_EVALUATED: "evaluate_readiness",
	EVT_STDINST_SNAPSHOT_CREATED: "create_snapshot",
	EVT_STDINST_PUBLICATION_LOCK_APPLIED: "apply_publication_lock",
	EVT_STDINST_ADDENDUM_IMPACT_ANALYSED: "analyse_addendum_impact",
	EVT_STDINST_OUTPUTS_SUPERSEDED: "supersede_output",
	EVT_STDINST_DENIED_EDIT_ATTEMPT: "denied_edit",
	EVT_STDINST_DENIED_DOWNSTREAM_RULE_INJECTION: "denied_downstream_rule_injection",
}
