#!/usr/bin/env python3
"""Build kentender_core/public/js/analytics/analytics_icons.js from the Analytics boards' inline icons.

ANL-CHG-001 v0.8 plan Phase 4 (ANL §10A.1 rule 7). The five boards under
`design/Analytics/*.dc.html` draw every icon as an inline Lucide path. The page needs the same
artwork under names, including the five area icons used on the tab, the summary column and the
region titles: Needs, Departmental planning, Annual planning, Requisitions, Tender proceedings.

Each icon is identified by the start of its markup, so a change to a board's artwork makes the
build stop until the name table below is revisited. The area-to-icon pairing is checked against
the tab labels the boards draw, not assumed.

    python3 scripts/analytics_icons_js.py            # rewrite
    python3 scripts/analytics_icons_js.py --check    # exit 1 if out of date
"""

from __future__ import annotations

import glob
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOARDS = "docs/mvp-1-r1/19_analytics/design/Analytics/*.dc.html"
TARGET = ROOT / "kentender_core/kentender_core/public/js/analytics/analytics_icons.js"

#: start of the icon's markup in the boards -> Lucide name
NAMES = {
	'<circle cx="12" cy="12" r="10"></circle><path d="M12 6v6l4 2">': "clock",
	'<path d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z">': "building-2",
	'<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8">': "refresh-cw",
	'<path d="M15 14c.2-1 .7-1.7 1.5-2.5': "lightbulb",
	'<rect width="8" height="4" x="8" y="2" rx="1" ry="1">': "clipboard-list",
	'<path d="M8 2v4"></path><path d="M16 2v4"></path><rect width="18" height="18" x="3" y="4" rx="2">': "calendar-days",
	'<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z">': "file-check",
	'<path d="m3 11 18-5v12L3 14v-3z">': "megaphone",
	'<path d="M5 22h14"></path><path d="M5 2h14">': "hourglass",
	'<line x1="10" x2="14" y1="2" y2="2">': "timer",
	'<circle cx="12" cy="12" r="10"></circle><path d="M12 16v-4">': "info",
	'<path d="m6 9 6 6 6-6">': "chevron-down",
	'<path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1">': "wallet",
	'<path d="M3 3v16a2 2 0 0 0 2 2h16">': "chart-column",
	'<path d="M3 12h.01"></path><path d="M3 18h.01">': "list",
	'<circle cx="11" cy="11" r="8"></circle><path d="m21 21-4.3-4.3">': "search",
	'<polyline points="22 12 16 12 14 15 10 15 8 12 2 12">': "inbox",
	'<circle cx="12" cy="12" r="10"></circle><path d="m15 9-6 6">': "circle-x",
	'<rect width="18" height="11" x="3" y="11" rx="2" ry="2">': "lock",
	'<path d="M18 6 6 18"></path><path d="m6 6 12 12">': "x",
}

#: Tab label the boards draw -> area key the page uses -> icon name. The boards are checked against this.
AREAS = {
	"Needs": ("needs", "lightbulb"),
	"Departmental planning": ("departmental_planning", "clipboard-list"),
	"Annual planning": ("annual_planning", "calendar-days"),
	"Requisitions": ("requisitions", "file-check"),
	"Tender proceedings": ("tender_proceedings", "megaphone"),
}


def _tidy(inner: str) -> str:
	return re.sub(r"></(path|circle|line|polyline|rect)>", "/>", re.sub(r"\s+", " ", inner.strip()))


def _name(inner: str) -> str:
	match = [name for start, name in NAMES.items() if inner.strip().startswith(start)]
	if len(match) != 1:
		raise SystemExit(f"icon in a board with no unique name: {inner.strip()[:90]}")
	return match[0]


def build() -> str:
	boards = sorted(glob.glob(str(ROOT / BOARDS)))
	if len(boards) != 6:
		raise SystemExit(f"expected the six Analytics board files, found {len(boards)}")
	icons: dict[str, str] = {}
	tabs: dict[str, str] = {}
	for board in boards:
		text = Path(board).read_text(encoding="utf-8")
		for inner in re.findall(r'<svg\b[^>]*class="kt-icon[^"]*"[^>]*>(.*?)</svg>', text, flags=re.S):
			name = _name(inner)
			markup = _tidy(inner)
			if icons.setdefault(name, markup) != markup:
				raise SystemExit(f"icon {name} is drawn two ways across the boards")
		for svg_inner, label in re.findall(r'<label class="kt-tab"><input[^>]*>\s*<svg\b[^>]*>(.*?)</svg>([^<]+)</label>', text, flags=re.S):
			tabs[label.strip()] = _name(svg_inner)
	missing = sorted(set(NAMES.values()) - set(icons))
	if missing:
		raise SystemExit(f"named icons not found in the boards: {missing}")
	for label, (_, icon) in AREAS.items():
		if tabs.get(label) != icon:
			raise SystemExit(f"the boards draw the {label!r} tab with {tabs.get(label)!r}, not {icon!r}")
	body = ",\n".join(f"\t{json.dumps(name)}: {json.dumps(icons[name])}" for name in sorted(icons))
	areas = ",\n".join(f"\t{key}: {json.dumps(icon)}" for key, icon in AREAS.values())
	return (
		"// GENERATED by scripts/analytics_icons_js.py from design/Analytics/*.dc.html (ANL-CHG-001 v0.8 plan Phase 4).\n"
		"// Lucide icons, viewBox 0 0 24 24, drawn by the .kt-icon class in kt_analytics_ds.bundle.css.\n"
		"// Do not edit by hand. One icon per area (ANL §10A.1 rule 7), as the boards draw the tabs.\n"
		f"export const ANALYTICS_ICONS = {{\n{body},\n}};\n"
		f"export const ANALYTICS_AREA_ICONS = {{\n{areas},\n}};\n"
		"export const ANALYTICS_ICON_VIEWBOX = \"0 0 24 24\";\n"
	)


if __name__ == "__main__":
	js = build()
	if "--check" in sys.argv:
		sys.exit(0 if TARGET.exists() and TARGET.read_text(encoding="utf-8") == js else 1)
	TARGET.parent.mkdir(parents=True, exist_ok=True)
	TARGET.write_text(js, encoding="utf-8")
	print(f"wrote {TARGET.relative_to(ROOT)}: {js.count(chr(10))} lines")
