#!/usr/bin/env python3
"""Build kentender_core/public/js/home/home_icons.js from the Home board's inline icons.

HOME-CHG-001 v0.6 plan Phase 1A. The board (`design/Home/Home.dc.html`) draws every
icon as an inline Lucide path, including three the design system's own icon list
lacks (clock, list-checks, calendar-clock). The page needs the same artwork under
names. Each icon is identified by the start of its path data, so a change to the
board's artwork makes `--check` fail until the name table below is revisited.

    python3 scripts/home_icons_js.py            # rewrite
    python3 scripts/home_icons_js.py --check    # exit 1 if out of date
"""

from __future__ import annotations

import glob
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOARD = ROOT / "docs/mvp-1-r1/18_home_page/design/Home/Home.dc.html"
TARGET = ROOT / "kentender_core/kentender_core/public/js/home/home_icons.js"
#: The board has no row for these modules, but the spec gives each module one icon "the same as on their own pages"
#: (HOME §10B.1): Strategy, Budget & Funding and Planning come from the design system's own icon list.
FROM_DESIGN_SYSTEM = ("target", "wallet", "clipboard-list", "users")

#: start of the icon's markup in the board -> Lucide name
NAMES = {
	'<path d="m3 11 18-5v12L3 14v-3z">': "megaphone",
	'<path d="m3 17 2 2 4-4">': "list-checks",
	'<circle cx="12" cy="12" r="10"></circle><path d="M12 6v6l4 2">': "clock",
	'<path d="M5 22h14">': "hourglass",
	'<path d="M3.85 8.62a4 4 0 0 1 4.78-4.77': "badge-check",
	'<path d="m16 16 3-8 3 8c-.87.65': "scale",
	'<path d="M2.062 12.348a1 1 0 0 1 0-.696': "eye",
	'<path d="M5 12h14">': "arrow-right",
	'<path d="M3 3v16a2 2 0 0 0 2 2h16">': "chart-column",
	'<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14': "triangle-alert",
	'<path d="M21 7.5V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14': "calendar-clock",
	'<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12': "file-check",
	'<circle cx="12" cy="12" r="10"></circle><path d="m9 12 2 2 4-4">': "circle-check",
	'<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8">': "refresh-cw",
	'<polyline points="22 12 16 12 14 15 10 15 8 12 2 12">': "inbox",
	'<circle cx="12" cy="12" r="10"></circle><line x1="12" x2="12" y1="8" y2="12">': "circle-alert",
	'<path d="M15 14c.2-1 .7-1.7 1.5-2.5': "lightbulb",
	'<path d="m6 9 6 6 6-6">': "chevron-down",
	'<circle cx="11" cy="11" r="8"></circle><path d="m21 21-4.3-4.3">': "search",
	'<circle cx="12" cy="12" r="10"></circle><path d="m15 9-6 6">': "circle-x",
	'<rect width="18" height="11" x="3" y="11" rx="2" ry="2">': "lock",
}


def build() -> str:
	board = BOARD.read_text(encoding="utf-8")
	inners = list(dict.fromkeys(m.strip() for m in re.findall(r'<svg\b[^>]*class="kt-icon[^"]*"[^>]*>(.*?)</svg>', board, flags=re.S)))
	icons: dict[str, str] = {}
	for inner in inners:
		match = [name for start, name in NAMES.items() if inner.startswith(start)]
		if len(match) != 1:
			raise SystemExit(f"icon in the board with no unique name: {inner[:90]}")
		icons[match[0]] = re.sub(r"></(path|circle|line|polyline|rect)>", "/>", re.sub(r"\s+", " ", inner))
	pack = json.loads(Path(sorted(glob.glob(str(ROOT / "docs/mvp-1-r1/18_home_page/design/_ds/kentender-industry-*/assets/icons/lucide-paths.json")))[0]).read_text(encoding="utf-8"))
	for name in FROM_DESIGN_SYSTEM:
		icons[name] = re.sub(r"\s+/>", "/>", re.sub(r"\s+", " ", pack[name].strip()))
	missing = sorted(set(NAMES.values()) - set(icons))
	if missing:
		raise SystemExit(f"named icons not found in the board: {missing}")
	body = ",\n".join(f"\t{json.dumps(name)}: {json.dumps(icons[name])}" for name in sorted(icons))
	return (
		"// GENERATED by scripts/home_icons_js.py from design/Home/Home.dc.html (HOME-CHG-001 v0.6 plan Phase 1A).\n"
		"// Lucide icons, stroke 1.75, viewBox 0 0 24 24, drawn by the .kt-icon class in kt_home_ds.bundle.css.\n"
		"// Do not edit by hand. Includes clock, list-checks and calendar-clock, which the design system's own icon list lacks.\n"
		f"export const HOME_ICONS = {{\n{body},\n}};\n"
		"export const HOME_ICON_VIEWBOX = \"0 0 24 24\";\n"
	)


if __name__ == "__main__":
	js = build()
	if "--check" in sys.argv:
		sys.exit(0 if TARGET.exists() and TARGET.read_text(encoding="utf-8") == js else 1)
	TARGET.parent.mkdir(parents=True, exist_ok=True)
	TARGET.write_text(js, encoding="utf-8")
	print(f"wrote {TARGET.relative_to(ROOT)}: {js.count(chr(10))} lines")
