# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""TPR-CHG-001 v0.6 §7.4/§8.4 — Tender evidence requirements: rows fixed by
the template, rows generated by the officer's Task 4 switches, and the
officer's own additional rows. Every row links to a visible inherited ID;
an unlinked row cannot exist, and no row creates a hidden criterion — its
label and link are published (TPR-AC-011/017/018, SMOKE-07)."""

from __future__ import annotations

from typing import Any

from frappe.utils import cstr

from kentender_procurement.tender_preparation.services import snapshot as snap

SOURCE_FIXED = "Fixed by template"
SOURCE_GENERATED = "Generated by officer choice"
SOURCE_ADDITIONAL = "Additional officer evidence"
EVIDENCE_TYPES = ("Declaration", "Certificate", "Datasheet or brochure", "Schedule or form", "Other document")
LINK_TYPES = tuple(snap.VISIBLE_TYPES)


def _row(*, row_id: str, label: str, evidence_type: str, link_type: str, link_id: str, source: str, mandatory: bool = True) -> dict[str, Any]:
	return {
		"evidence_requirement_id": row_id, "evidence_label": label, "evidence_type": evidence_type,
		"linked_requirement_type": link_type, "linked_requirement_id": link_id, "mandatory": 1 if mandatory else 0, "source": source,
	}


def generated_rows(state: dict[str, Any], snapshot: dict[str, Any]) -> list[dict[str, Any]]:
	"""Fixed + switch-generated rows, deterministic for a given state."""
	rows: list[dict[str, Any]] = []
	items = snapshot.get("items") or []
	technical = snapshot.get("technical_requirements") or []
	months = snapshot.get("minimum_warranty_months")
	n = 0

	def add(label, evidence_type, link_type, link_id, source):
		nonlocal n
		n += 1
		rows.append(_row(row_id=f"EV-G{n:03d}", label=label, evidence_type=evidence_type, link_type=link_type, link_id=link_id, source=source))

	# Fixed by template — always (§8.4 "Warranty confirmation required — Yes, always required").
	for item in items:
		add(f"Warranty confirmation — minimum {months} months — {item.get('item_name')}", "Declaration", "Equipment item", item.get("requisition_item_id"), SOURCE_FIXED)
	if state.get("manufacturer_authorisation_required"):
		for item in items:
			add(f"Manufacturer's authorisation — {item.get('item_name')}", "Certificate", "Equipment item", item.get("requisition_item_id"), SOURCE_GENERATED)
	if state.get("datasheets_required"):
		for row in technical:
			add(f"Datasheet or brochure evidencing {row.get('technical_requirement_id')}", "Datasheet or brochure", "Technical requirement", row.get("technical_requirement_id"), SOURCE_GENERATED)
	if state.get("after_sales_evidence_required"):
		choice = cstr(state.get("after_sales_evidence")) or "After-sales support evidence"
		for item in items:
			add(f"After-sales support evidence — {choice} — {item.get('item_name')}", "Other document", "Equipment item", item.get("requisition_item_id"), SOURCE_GENERATED)
	return rows


def validate_additional(values: dict[str, Any], snapshot: dict[str, Any]) -> tuple[dict[str, Any], dict[str, str]]:
	errors: dict[str, str] = {}
	clean: dict[str, Any] = {}
	label = values.get("evidence_label")
	if not isinstance(label, str) or not (3 <= len(label.strip()) <= 160) or any(t in label for t in ("<", ">", "**", "```")):
		errors["evidence_label"] = "Enter plain text of 3–160 characters."
	else:
		clean["evidence_label"] = label.strip()
	if values.get("evidence_type") not in EVIDENCE_TYPES:
		errors["evidence_type"] = "Choose one of: " + ", ".join(EVIDENCE_TYPES) + "."
	else:
		clean["evidence_type"] = values["evidence_type"]
	link_type = values.get("linked_requirement_type")
	if link_type not in LINK_TYPES:
		errors["linked_requirement_type"] = "Choose one of: " + ", ".join(LINK_TYPES) + "."
	else:
		clean["linked_requirement_type"] = link_type
		visible = snap.visible_ids(snapshot).get(link_type, set())
		link_id = cstr(values.get("linked_requirement_id")).strip()
		if link_id not in visible:
			errors["linked_requirement_id"] = "Choose a visible inherited requirement of that type."
		else:
			clean["linked_requirement_id"] = link_id
	mandatory = values.get("mandatory", True)
	if isinstance(mandatory, bool) or mandatory in (0, 1, "0", "1", "true", "false"):
		clean["mandatory"] = 1 if mandatory in (True, 1, "1", "true") else 0
	else:
		errors["mandatory"] = "Choose Yes or No."
	for name in set(values) - {"evidence_label", "evidence_type", "linked_requirement_type", "linked_requirement_id", "mandatory"}:
		errors[name] = "Unknown field."
	return clean, errors


def rebuild(version, snapshot: dict[str, Any]) -> None:
	"""Replace every fixed/generated row from the current Task 4 state; keep
	the officer's additional rows (re-numbered after them)."""
	state = {f: version.get(f) for f in ("manufacturer_authorisation_required", "datasheets_required", "after_sales_evidence_required", "after_sales_evidence")}
	additional = [r for r in version.get("evidence_requirements") or [] if r.source == SOURCE_ADDITIONAL]
	version.set("evidence_requirements", [])
	order = 0
	for row in generated_rows(state, snapshot):
		order += 1
		version.append("evidence_requirements", {**row, "row_order": order})
	for row in additional:
		order += 1
		version.append(
			"evidence_requirements",
			{
				"evidence_requirement_id": row.evidence_requirement_id, "evidence_label": row.evidence_label, "evidence_type": row.evidence_type,
				"linked_requirement_type": row.linked_requirement_type, "linked_requirement_id": row.linked_requirement_id,
				"mandatory": row.mandatory, "source": SOURCE_ADDITIONAL, "row_order": order,
			},
		)


def next_additional_id(version) -> str:
	existing = {r.evidence_requirement_id for r in version.get("evidence_requirements") or [] if r.source == SOURCE_ADDITIONAL}
	n = 1
	while f"EV-A{n:03d}" in existing:
		n += 1
	return f"EV-A{n:03d}"


def rows_as_dicts(version) -> list[dict[str, Any]]:
	return [
		{
			"evidence_requirement_id": r.evidence_requirement_id, "evidence_label": r.evidence_label, "evidence_type": r.evidence_type,
			"linked_requirement_type": r.linked_requirement_type, "linked_requirement_id": r.linked_requirement_id,
			"mandatory": bool(r.mandatory), "source": r.source, "row_order": r.row_order,
		}
		for r in sorted(version.get("evidence_requirements") or [], key=lambda x: x.row_order or 0)
	]


def technical_ids_with_evidence(version) -> set[str]:
	return {r.linked_requirement_id for r in version.get("evidence_requirements") or [] if r.linked_requirement_type == "Technical requirement"}


def unlinked_rows(version, snapshot: dict[str, Any]) -> list[str]:
	visible = snap.visible_ids(snapshot)
	return [r.evidence_requirement_id for r in version.get("evidence_requirements") or [] if r.linked_requirement_id not in visible.get(r.linked_requirement_type, set())]
