# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""KT-STD-001 v1.9 §3B.7 / NDS-CHG-001 v1.15 §5.5 — the Departmental Needs
dead-end matrix.

Needs are driven through the real commands into every state §5.5 names
(plus Planning's two positions for a Need accepted after its department's
plan, owner decision 26 Sep 2026), and at each state every responsibility
able to read the Need reads its page. For every row:

1. the reader has an enabled action, or a next step naming a holder and a
   reason (`kentender_core.services.next_step.problems`);
2. every blocker carries a reason code and a fix (same helper);
3. every route fix opens a Needs, departmental-plan or annual-plan-item page;
4. the next step's stage is the stage the tracker shows as current;
5. no reader is told to wait for themselves;
6. a technical reader is never given a turn (§3B.6).

The rules alone accept a "Done" answer, which is how the late Need went
unseen, so the one actor whose turn each state is is asserted as well. The
matrix is written to
`docs/mvp-1-r1/01_departmental_needs/evidence/v1_15/dead_end_matrix.md`.
"""

from __future__ import annotations

import os

import frappe

from kentender_core.services import next_step as ns
from kentender_procurement.departmental_needs.errors import DepartmentalNeedError
from kentender_procurement.departmental_needs.seeds.kentender_mvp_r1 import (
	ACTING_REVIEWER,
	AUDITOR,
	AUTHOR,
	PLANNER,
	REVIEWER,
)
from kentender_procurement.departmental_needs.services import lifecycle, workspace
from kentender_procurement.departmental_needs.services.usage import project_planning_intake
from kentender_procurement.departmental_needs.tests.test_departmental_needs_lifecycle import (
	REASON,
	DepartmentalNeedsCommandCase,
)

READERS = (
	("Departmental Author", AUTHOR),
	("Head of User Department", REVIEWER),
	("Head of another department", ACTING_REVIEWER),
	("Procurement Planner", PLANNER),
	("Auditor", AUDITOR),
	("Technical reader", "Administrator"),
)
ROUTES = {"departmental-needs", "departmental-procurement-plan", "procurement-plan-item"}
TURNS = (ns.KIND_YOUR_TURN, ns.KIND_BLOCKED)
PLAN = "DPP-NDS-MATRIX-2027-001"
MATRIX = os.path.join(
	os.path.dirname(frappe.get_app_path("kentender_procurement")), "..", "docs", "mvp-1-r1",
	"01_departmental_needs", "evidence", "v1_15", "dead_end_matrix.md",
)


class TestDepartmentalNeedsDeadEndMatrix(DepartmentalNeedsCommandCase):
	rows: list[tuple[str, str, str, str, str]] = []

	@classmethod
	def tearDownClass(cls):
		if cls.rows:
			os.makedirs(os.path.dirname(MATRIX), exist_ok=True)
			with open(MATRIX, "w", encoding="utf-8") as out:
				out.write("# Departmental Needs dead-end matrix — NDS-CHG-001 v1.15 / KT-STD-001 v1.9 §3B.7\n\n")
				out.write("Generated by `departmental_needs/tests/test_departmental_needs_dead_end_matrix.py`. ")
				out.write("One row per state and reader; a reader with no access to the Need is listed as such.\n\n")
				out.write("| State | Reader | Kind | Next step | Result |\n|---|---|---|---|---|\n")
				for state, reader, kind, headline, result in cls.rows:
					out.write(f"| {state} | {reader} | {kind} | {headline.replace('|', '/')} | {result} |\n")
		super().tearDownClass()

	# ------------------------------------------------------------------

	def _read(self, need: str, user: str):
		frappe.set_user(user)
		try:
			return workspace.get_need(need=need, user=user)
		except (frappe.PermissionError, frappe.DoesNotExistError, DepartmentalNeedError):
			return None
		finally:
			frappe.set_user("Administrator")

	def check(self, state: str, need: str, *, turn: tuple[str, ...] = ()) -> list[str]:
		failures = []
		for reader, user in READERS:
			view = self._read(need, user)
			if view is None:
				self.rows.append((state, reader, "—", "cannot read this Need", "pass"))
				continue
			step = view.get("next_step")
			journey = view.get("journey") or {}
			problems = ns.problems(step, has_enabled_action=bool(view.get("actions")))
			for fix in (step or {}).get("fixes") or []:
				if fix.get("kind") == ns.FIX_ROUTE and (not fix.get("target") or fix["target"][0] not in ROUTES):
					problems.append(f"fix {fix.get('fix_id')} opens no Needs or plan page")
			kind = (step or {}).get("kind", "")
			current = journey.get("current")
			if kind in (*TURNS, ns.KIND_WAITING) and current and step.get("stage") and step["stage"] != current:
				problems.append(f"stage {step['stage']} is not the tracker's {current}")
			if kind == ns.KIND_WAITING and frappe.db.get_value("User", user, "full_name") in ((step.get("holder") or {}).get("people") or []):
				problems.append("the reader is told to wait for themselves")
			if user == "Administrator" and kind in TURNS:
				problems.append("a technical reader was given a turn")
			if reader in turn and kind not in TURNS:
				problems.append(f"expected this reader's turn, got {kind or 'none'}")
			result = "pass" if not problems else "FAIL: " + "; ".join(problems)
			if problems:
				failures.append(f"{state} / {reader}: {'; '.join(problems)}")
			self.rows.append((state, reader, kind or "none", (step or {}).get("headline") or "—", result))
		return failures

	def position(self, need: str, position: str):
		doc = frappe.get_doc("Departmental Need", need)
		frappe.set_user(PLANNER)
		try:
			project_planning_intake(
				departmental_need=need, need_revision=doc.current_accepted_revision, position=position,
				departmental_plan=PLAN, source_event_id=self.key(), source_event_time=frappe.utils.now(),
			)
		finally:
			frappe.set_user("Administrator")

	def record_version(self, need: str) -> int:
		return frappe.db.get_value("Departmental Need", need, "record_version")

	# ------------------------------------------------------------------

	def test_every_need_state_leaves_every_reader_somewhere_to_go(self):
		failures = []

		draft = self.create()
		failures += self.check("Draft", draft["need"], turn=("Departmental Author",))

		submitted = self.submit(self.create())
		failures += self.check("Submitted", submitted["need"], turn=("Head of User Department",))

		returned = self.decide(self.submit(self.create()), "return", reason=REASON)
		failures += self.check("Returned", returned["need"], turn=("Departmental Author",))

		declined = self.decide(self.submit(self.create()), "decline", reason=REASON)
		failures += self.check("Not taken forward", declined["need"])

		frappe.set_user(AUTHOR)
		withdrawn = self.create()
		lifecycle.withdraw_need(need=withdrawn["need"], expected_version=withdrawn["record_version"], idempotency_key=self.key())
		failures += self.check("Withdrawn", withdrawn["need"])

		accepted = self.accepted()
		need = accepted["need"]
		failures += self.check("Accepted for planning", need)

		# Owner decision 26 Sep 2026 — accepted after the department's plan.
		self.position(need, "Update required")
		failures += self.check("Accepted — not in the accepted departmental plan", need, turn=("Departmental Author", "Head of User Department"))
		self.position(need, "After current submission")
		failures += self.check("Accepted — departmental plan with Procurement", need, turn=("Procurement Planner",))
		self.position(need, "No update needed")

		frappe.set_user(AUTHOR)
		opened = lifecycle.create_accepted_need_successor(need=need, expected_version=self.record_version(need), idempotency_key=self.key())
		failures += self.check("Accepted — update in progress", need, turn=("Departmental Author",))
		frappe.set_user(AUTHOR)
		saved = lifecycle.update_need(
			need=need, expected_version=opened["record_version"], idempotency_key=self.key(),
			**self.content(required_by_date="2027-09-15"),
		)
		lifecycle.submit_need(need=need, expected_version=saved["record_version"], idempotency_key=self.key())
		failures += self.check("Accepted — update submitted", need, turn=("Head of User Department",))

		frappe.set_user(AUTHOR)
		other = self.accepted()
		frappe.set_user(AUTHOR)
		lifecycle.request_withdrawal(need=other["need"], expected_version=other["record_version"], idempotency_key=self.key(), reason=REASON)
		failures += self.check("Accepted — withdrawal requested", other["need"], turn=("Head of User Department",))

		# Still in the annual plan: the withdrawal waits on a Planning change.
		third = self.accepted()
		revision = frappe.db.get_value("Departmental Need", third["need"], "current_accepted_revision")
		self.include_in_active_plan(third["need"], revision)
		frappe.set_user(AUTHOR)
		requested = lifecycle.request_withdrawal(need=third["need"], expected_version=self.record_version(third["need"]), idempotency_key=self.key(), reason=REASON)
		frappe.set_user(REVIEWER)
		lifecycle.decide_withdrawal(
			need=third["need"], task=requested["task"], decision="evaluate", expected_version=self.record_version(third["need"]),
			decision_token=self.token(requested["task"]), idempotency_key=self.key(),
		)
		failures += self.check("Accepted — withdrawal waiting for a Planning change", third["need"], turn=("Head of User Department", "Procurement Planner"))

		self.assertEqual(failures, [], "\n".join(failures))
