# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""PUB-1000 — Publication audit ``event_type`` values and pack §18 ``event_code`` mapping.

``Audit Event.event_type`` uses the ``TENDER_PUBLICATION_*`` namespace for stable queries.
Metadata includes ``event_code`` with the Cursor pack §18 semantic name where applicable.
"""

from __future__ import annotations

from kentender_procurement.tender_management.security.authorization.denial_codes import (
	DenialCode,
)
from kentender_procurement.tender_management.security.audit.event_catalog import (
	AuditEventCode,
)

# --- Pack §18 semantic names (stored in metadata["event_code"]) -----------------
PACK_PUBLICATION_READINESS_RUN = AuditEventCode.PUBLICATION_READINESS_RUN
PACK_PUBLICATION_READINESS_BLOCKED = AuditEventCode.PUBLICATION_READINESS_BLOCKED
PACK_PUBLICATION_READINESS_PASSED = "PUBLICATION_READINESS_PASSED"
PACK_CONFIGURATION_SNAPSHOT_CREATED = "CONFIGURATION_SNAPSHOT_CREATED"
PACK_TENDER_SUBMITTED_FOR_APPROVAL = AuditEventCode.TENDER_SUBMITTED_FOR_APPROVAL
PACK_APPROVAL_REVIEW_OPENED = AuditEventCode.APPROVAL_REVIEW_OPENED
PACK_APPROVAL_RETURNED = AuditEventCode.APPROVAL_RETURNED
PACK_APPROVAL_REJECTED = AuditEventCode.APPROVAL_REJECTED
PACK_APPROVAL_GRANTED = AuditEventCode.APPROVAL_GRANTED
PACK_PUBLICATION_ATTEMPTED = AuditEventCode.PUBLICATION_ATTEMPTED
PACK_PUBLICATION_DENIED = AuditEventCode.PUBLICATION_DENIED
PACK_PUBLICATION_SNAPSHOT_CREATED = AuditEventCode.PUBLICATION_SNAPSHOT_CREATED
PACK_OUTPUTS_MARKED_PUBLISHED = "OUTPUTS_MARKED_PUBLISHED"
PACK_STD_INSTANCE_PUBLISHED_LOCKED = "STD_INSTANCE_PUBLISHED_LOCKED"
PACK_TENDER_PUBLISHED = AuditEventCode.TENDER_PUBLISHED
PACK_EVIDENCE_PACKAGE_ASSEMBLED = AuditEventCode.EVIDENCE_PACKAGE_ASSEMBLED
PACK_EVIDENCE_PACKAGE_EXPORTED = AuditEventCode.EVIDENCE_PACKAGE_EXPORTED
PACK_POST_PUBLICATION_EDIT_DENIED = AuditEventCode.POST_PUBLICATION_EDIT_DENIED
PACK_ADDENDUM_REQUIRED_NOTICE = "ADDENDUM_REQUIRED_NOTICE"
PACK_AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
# Operational (not in pack §18 table; stable metadata for orchestration rows)
PACK_RETURN_TO_PREPARATION_ORCHESTRATED = "RETURN_TO_PREPARATION_ORCHESTRATED"
PACK_APPROVAL_CLARIFICATION_REQUESTED = "APPROVAL_CLARIFICATION_REQUESTED"

# --- Audit Event.event_type (DB) -------------------------------------------------
AUDIT_TENDER_PUBLICATION_READINESS_RUN = "TENDER_PUBLICATION_READINESS_RUN"
AUDIT_TENDER_PUBLICATION_READINESS_BLOCKED = "TENDER_PUBLICATION_READINESS_BLOCKED"
AUDIT_TENDER_PUBLICATION_READINESS_PASSED = "TENDER_PUBLICATION_READINESS_PASSED"
AUDIT_TENDER_PUBLICATION_CONFIGURATION_SNAPSHOT_CREATED = "TENDER_PUBLICATION_CONFIGURATION_SNAPSHOT_CREATED"
AUDIT_TENDER_PUBLICATION_SUBMITTED_FOR_APPROVAL = "TENDER_PUBLICATION_SUBMITTED_FOR_APPROVAL"
AUDIT_TENDER_PUBLICATION_APPROVAL_REVIEW_OPENED = "TENDER_PUBLICATION_APPROVAL_REVIEW_OPENED"
AUDIT_TENDER_PUBLICATION_PUBLICATION_ATTEMPTED = "TENDER_PUBLICATION_PUBLICATION_ATTEMPTED"
AUDIT_TENDER_PUBLICATION_PUBLICATION_DENIED = "TENDER_PUBLICATION_PUBLICATION_DENIED"
AUDIT_TENDER_PUBLICATION_PUBLICATION_SNAPSHOT_CREATED = "TENDER_PUBLICATION_PUBLICATION_SNAPSHOT_CREATED"
AUDIT_TENDER_PUBLICATION_OUTPUTS_MARKED_PUBLISHED = "TENDER_PUBLICATION_OUTPUTS_MARKED_PUBLISHED"
AUDIT_TENDER_PUBLICATION_STD_INSTANCE_PUBLISHED_LOCKED = "TENDER_PUBLICATION_STD_INSTANCE_PUBLISHED_LOCKED"
AUDIT_TENDER_PUBLICATION_EVIDENCE_PACKAGE_ASSEMBLED = "TENDER_PUBLICATION_EVIDENCE_PACKAGE_ASSEMBLED"
AUDIT_TENDER_PUBLICATION_EVIDENCE_PACKAGE_EXPORTED = "TENDER_PUBLICATION_EVIDENCE_PACKAGE_EXPORTED"
AUDIT_TENDER_PUBLICATION_ADDENDUM_REQUIRED_NOTICE = "TENDER_PUBLICATION_ADDENDUM_REQUIRED_NOTICE"

# PUB-0310 / existing identifiers (unchanged for backward compatibility)
AUDIT_TENDER_PUBLICATION_APPROVAL_GRANTED = "TENDER_PUBLICATION_APPROVAL_GRANTED"
AUDIT_TENDER_PUBLICATION_APPROVAL_RETURNED = "TENDER_PUBLICATION_APPROVAL_RETURNED"
AUDIT_TENDER_PUBLICATION_APPROVAL_REJECTED = "TENDER_PUBLICATION_APPROVAL_REJECTED"
AUDIT_TENDER_PUBLICATION_APPROVAL_CLARIFICATION_REQUESTED = "TENDER_PUBLICATION_APPROVAL_CLARIFICATION_REQUESTED"
AUDIT_TENDER_PUBLICATION_RETURN_TO_PREPARATION = "TENDER_PUBLICATION_RETURN_TO_PREPARATION"
AUDIT_TENDER_PUBLICATION_TENDER_PUBLISHED = "TENDER_PUBLICATION_TENDER_PUBLISHED"

# PUB-0610 / PUB-0800 — metadata ``denial_code`` aligns with SEC-0200 pack §7.
DENIAL_POST_PUBLICATION_EDIT_ADDENDUM_REQUIRED = (
	DenialCode.POST_PUBLICATION_EDIT_DENIED_ADDENDUM_REQUIRED
)
AUDIT_POST_PUBLICATION_EDIT_DENIED = "TENDER_PUBLICATION_POST_PUBLICATION_EDIT_DENIED"
AUDIT_TENDER_PUBLICATION_AUTHORIZATION_DENIED = "TENDER_PUBLICATION_AUTHORIZATION_DENIED"

EVENT_TYPE_TO_PACK_EVENT_CODE: dict[str, str] = {
	AUDIT_TENDER_PUBLICATION_READINESS_RUN: PACK_PUBLICATION_READINESS_RUN,
	AUDIT_TENDER_PUBLICATION_READINESS_BLOCKED: PACK_PUBLICATION_READINESS_BLOCKED,
	AUDIT_TENDER_PUBLICATION_READINESS_PASSED: PACK_PUBLICATION_READINESS_PASSED,
	AUDIT_TENDER_PUBLICATION_CONFIGURATION_SNAPSHOT_CREATED: PACK_CONFIGURATION_SNAPSHOT_CREATED,
	AUDIT_TENDER_PUBLICATION_SUBMITTED_FOR_APPROVAL: PACK_TENDER_SUBMITTED_FOR_APPROVAL,
	AUDIT_TENDER_PUBLICATION_APPROVAL_REVIEW_OPENED: PACK_APPROVAL_REVIEW_OPENED,
	AUDIT_TENDER_PUBLICATION_APPROVAL_GRANTED: PACK_APPROVAL_GRANTED,
	AUDIT_TENDER_PUBLICATION_APPROVAL_RETURNED: PACK_APPROVAL_RETURNED,
	AUDIT_TENDER_PUBLICATION_APPROVAL_REJECTED: PACK_APPROVAL_REJECTED,
	AUDIT_TENDER_PUBLICATION_APPROVAL_CLARIFICATION_REQUESTED: PACK_APPROVAL_CLARIFICATION_REQUESTED,
	AUDIT_TENDER_PUBLICATION_RETURN_TO_PREPARATION: PACK_RETURN_TO_PREPARATION_ORCHESTRATED,
	AUDIT_TENDER_PUBLICATION_PUBLICATION_ATTEMPTED: PACK_PUBLICATION_ATTEMPTED,
	AUDIT_TENDER_PUBLICATION_PUBLICATION_DENIED: PACK_PUBLICATION_DENIED,
	AUDIT_TENDER_PUBLICATION_PUBLICATION_SNAPSHOT_CREATED: PACK_PUBLICATION_SNAPSHOT_CREATED,
	AUDIT_TENDER_PUBLICATION_OUTPUTS_MARKED_PUBLISHED: PACK_OUTPUTS_MARKED_PUBLISHED,
	AUDIT_TENDER_PUBLICATION_STD_INSTANCE_PUBLISHED_LOCKED: PACK_STD_INSTANCE_PUBLISHED_LOCKED,
	AUDIT_TENDER_PUBLICATION_TENDER_PUBLISHED: PACK_TENDER_PUBLISHED,
	AUDIT_TENDER_PUBLICATION_EVIDENCE_PACKAGE_ASSEMBLED: PACK_EVIDENCE_PACKAGE_ASSEMBLED,
	AUDIT_TENDER_PUBLICATION_EVIDENCE_PACKAGE_EXPORTED: PACK_EVIDENCE_PACKAGE_EXPORTED,
	AUDIT_POST_PUBLICATION_EDIT_DENIED: PACK_POST_PUBLICATION_EDIT_DENIED,
	AUDIT_TENDER_PUBLICATION_ADDENDUM_REQUIRED_NOTICE: PACK_ADDENDUM_REQUIRED_NOTICE,
	AUDIT_TENDER_PUBLICATION_AUTHORIZATION_DENIED: PACK_AUTHORIZATION_DENIED,
}
