# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""KT-STD-001 v1.8 §3B.7 / TPR-CHG-001 v0.12 §5.9 — the Tenders dead-end
matrix (plan Phase 2; TPR12-AC-001..010).

One Tender is walked with real commands through every §5.9 state its
lifecycle reaches — Draft (editor and review), returned and resubmitted,
HOPF approval, AO authorisation, publication part-confirmed, Published —
open, an addendum at each status, a material addendum and its cancellation
review, a supplier clarification, and Cancelled — plus a Requisition
correction and a segregation walk in which one person prepared the Tender.
At each state every reader reads the screen that state opens on, and for
every row:

1. the reader has a next step naming a holder and a reason, or an action
   (`kentender_core.services.next_step.problems`);
2. every blocker carries a reason code and a fix (same helper);
3. every route fix opens a Tenders task or page;
4. the next step's stage is the stage the tracker shows as current;
5. no reader is told to wait for themselves;
6. a technical reader never gets a turn (§3B.6).

The matrix is written to
`docs/mvp-1-r1/11_tenders/evidence/v0_12/dead_end_matrix.md`.
"""

from __future__ import annotations

import os

import frappe
from frappe.tests import IntegrationTestCase

from kentender_core.services import next_step as ns
from kentender_procurement.tenders.services import addenda, cancellation, candidate_gateway, clarifications, configuration_gateway, correction, lifecycle, open_period_read, publication, read
from kentender_procurement.tenders.services import draft_commands as cmd
from kentender_procurement.tenders.services.errors import TendersError
from kentender_procurement.tenders.tests import fixtures as fx, sample

READERS = (
	("Procurement Officer", fx.OFFICER),
	("Head of Procurement Function", fx.HOPF),
	("Accounting Officer", fx.AO),
	("Officer, HOPF and AO in one person", fx.BOTH),
	("Auditor", fx.AUDITOR),
	("Departmental reader", fx.DEPARTMENTAL),
	("Outsider", fx.OUTSIDER),
	("Technical reader", "Administrator"),
)
TASK_ROUTES = {"details", "requirements", "review"}
PAGES = {"tenders", "procurement-requisitions", "system-setup", "std-templates"}
TURNS = (ns.KIND_YOUR_TURN, ns.KIND_BLOCKED)
CHANNELS = ("STATE_PORTAL", "MINISTRY_WEBSITE", "NOTICE_BOARD", "NATIONAL_NEWSPAPERS")
MATRIX = os.path.join(
	os.path.dirname(frappe.get_app_path("kentender_procurement")), "..", "docs", "mvp-1-r1", "11_tenders", "evidence", "v0_12", "dead_end_matrix.md",
)
ADDENDUM = {
	"change_class": "Administrative clarification", "affected_area": "Goods/delivery schedule", "affected_reference_key": "delivery_location",
	"revised_value": "Test Delivery Location — Tenders, 3rd Floor Procurement Stores", "reason": "The published address omitted the internal delivery point",
	"materiality_statement": "Same site; no change to scope, quantity, value or evaluation basis.",
}


class TestTendersDeadEndMatrix(IntegrationTestCase):
	rows: list[tuple[str, str, str, str, str]] = []

	@classmethod
	def setUpClass(cls):
		super().setUpClass()
		frappe.set_user("Administrator")
		fx.ensure_world()
		cls.addClassCleanup(fx.restore_site)

	@classmethod
	def tearDownClass(cls):
		if cls.rows:
			os.makedirs(os.path.dirname(MATRIX), exist_ok=True)
			with open(MATRIX, "w", encoding="utf-8") as out:
				out.write("# Tenders dead-end matrix — TPR-CHG-001 v0.12 / KT-STD-001 v1.8 §3B.7\n\n")
				out.write("Generated by `tenders/tests/test_dead_end_matrix.py` (`make tenders-dead-end-gate`). ")
				out.write("One row per state and reader, on the screen that state opens on; a reader with no access to the record is listed as such.\n\n")
				out.write("| State | Reader | Kind | Next step | Result |\n|---|---|---|---|---|\n")
				for state, reader, kind, headline, result in cls.rows:
					out.write(f"| {state} | {reader} | {kind} | {headline.replace('|', '/')} | {result} |\n")
		super().tearDownClass()

	def setUp(self):
		super().setUp()
		frappe.set_user("Administrator")
		fx.wipe_all()
		self.addCleanup(frappe.set_user, "Administrator")
		frappe.flags.kt_tenders_clock = "2027-04-20 10:00:00"
		self.addCleanup(setattr, frappe.flags, "kt_tenders_clock", None)

	# ------------------------------------------------------------------

	def _read(self, fn, user):
		try:
			return fn(user)
		except (frappe.PermissionError, frappe.DoesNotExistError, TendersError):
			return None

	def check(self, state: str, fn) -> list[str]:
		failures = []
		for reader, user in READERS:
			view = self._read(fn, user)
			if view is None or view.get("outcome") not in (None, "OK"):
				self.rows.append((state, reader, "—", "cannot read this record", "pass"))
				continue
			guidance = view.get("guidance") or {}
			step = guidance.get("next_step")
			journey = guidance.get("journey") or {}
			problems = ns.problems(step)
			for fix in [f for b in (step or {}).get("blockers") or [] for f in b.get("fixes") or []] + list((step or {}).get("fixes") or []):
				if fix.get("kind") != ns.FIX_ROUTE:
					continue
				target = fix.get("target")
				if isinstance(target, dict):
					if target.get("task") not in TASK_ROUTES:
						problems.append(f"fix {fix.get('fix_id')} opens no Tender task")
				elif not target or target[0] not in PAGES:
					problems.append(f"fix {fix.get('fix_id')} opens no Tenders page")
			kind = (step or {}).get("kind", "")
			current = journey.get("current")
			if kind in (*TURNS, ns.KIND_WAITING) and current and step.get("stage") and step["stage"] != current:
				problems.append(f"stage {step['stage']} is not the tracker's {current}")
			if kind == ns.KIND_WAITING and frappe.db.get_value("User", user, "full_name") in ((step.get("holder") or {}).get("people") or []):
				problems.append("the reader is told to wait for themselves")
			if user == "Administrator" and kind in TURNS:
				problems.append("a technical reader was given a turn")
			if not journey.get("stages"):
				problems.append("no journey")
			result = "pass" if not problems else "FAIL: " + "; ".join(problems)
			if problems:
				failures.append(f"{state} / {reader}: {'; '.join(problems)}")
			self.rows.append((state, reader, kind or "none", (step or {}).get("headline") or "—", result))
		return failures

	def record(self, name):
		return lambda user: read.get_tender(tender=name, user=user)

	def review(self, name):
		return lambda user: read.get_tender_review(tender=name, user=user)

	def publication_screen(self, name):
		return lambda user: publication.get_tender_publication(tender=name, user=user)

	def addendum(self, name, addendum):
		return lambda user: open_period_read.get_tender_addendum(tender=name, addendum=addendum, user=user)

	def clarification(self, name, clarification):
		return lambda user: open_period_read.get_tender_clarification(tender=name, clarification=clarification, user=user)

	def cancellation_screen(self, name):
		return lambda user: open_period_read.get_tender_cancellation(tender=name, user=user)

	# ------------------------------------------------------------------

	def _started(self, officer=fx.OFFICER):
		authorised = fx.authorised_handoff()
		started = cmd.start_tender(handoff=authorised["handoff"], idempotency_key=fx.key(), user=officer)
		return frappe.get_doc("Tender", started["tender"])

	def _save(self, root, officer=fx.OFFICER):
		cmd.save_tender_draft(tender=root.name, values=sample.officer_values(inspection_location=fx.LOCATION, contact_office=fx.CONTACT_OFFICE), expected_record_version=root.record_version, idempotency_key=fx.key(), user=officer)
		root.reload()

	def _confirm(self, root, channel, *, subject="publication", addendum=""):
		root.reload()
		online = channel in configuration_gateway.ONLINE_CHANNELS
		common = dict(available_at="2027-05-15 08:00:00", evidence_reference=f"REF-{channel}", evidence_file=fx.evidence_file(f"{channel}.png"), public_url=f"https://portal.example.test/{channel}" if online else "", url_not_applicable_reason="" if online else "Physical channel", expected_record_version=root.record_version, idempotency_key=fx.key(), attestation_confirmed=True, user=fx.HOPF)
		if subject == "publication":
			return publication.confirm_publication_channel(tender=root.name, channel=channel, package_digest=frappe.db.get_value("Tender Publication", root.publication, "package_digest"), **common)
		return addenda.confirm_addendum_publication_channel(tender=root.name, addendum=addendum, channel=channel, addendum_digest=frappe.db.get_value("Tender Addendum", addendum, "addendum_digest"), **common)

	# ------------------------------------------------------------------

	def test_every_tender_state_leaves_every_reader_somewhere_to_go(self):
		failures: list[str] = []
		root = self._started()
		failures += self.check("Draft — Tender details", self.record(root.name))
		self._save(root)
		failures += self.check("Draft — review, no must-fix", self.review(root.name))
		submitted = lifecycle.submit_tender_for_approval(tender=root.name, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.OFFICER)
		root.reload()
		failures += self.check("Awaiting procurement approval", self.review(root.name))
		lifecycle.return_tender_for_correction(tender=root.name, reason="Confirm whether manufacturer authorisation is necessary and update the supplier evidence requirement.", affected_task="Supplier and contract requirements", expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.HOPF, task=submitted["task"])
		root.reload()
		failures += self.check("Draft — returned for correction", self.record(root.name))
		submitted = lifecycle.submit_tender_for_approval(tender=root.name, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.OFFICER)
		root.reload()
		approved = lifecycle.approve_tender_package(tender=root.name, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.HOPF, task=submitted["task"])
		root.reload()
		failures += self.check("Approved — awaiting AO authorisation", self.publication_screen(root.name))
		publication.authorise_tender_publication(tender=root.name, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.AO, task=approved["task"])
		root.reload()
		frappe.flags.kt_tenders_clock = "2027-05-15 07:55:00"
		for channel in CHANNELS[:2]:
			self._confirm(root, channel)
		failures += self.check("Publication authorised — 2 of 4 confirmed", self.publication_screen(root.name))
		for channel in CHANNELS[2:]:
			self._confirm(root, channel)
		root.reload()
		self.assertEqual(root.overall_status, "Published — open")
		failures += self.check("Published — open", self.record(root.name))

		# a non-material addendum through every status
		frappe.flags.kt_tenders_clock = "2027-05-20 08:30:00"
		root.reload()
		name = addenda.create_addendum_draft(tender=root.name, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.OFFICER)["addendum"]["name"]
		root.reload()
		addenda.update_addendum_draft(tender=root.name, addendum=name, values=ADDENDUM, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.OFFICER)
		failures += self.check("Addendum — Draft", self.addendum(root.name, name))
		root.reload()
		addenda.submit_addendum_for_issue(tender=root.name, addendum=name, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.OFFICER)
		failures += self.check("Addendum — Awaiting issue", self.addendum(root.name, name))
		root.reload()
		addenda.issue_addendum(tender=root.name, addendum=name, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.HOPF)
		failures += self.check("Addendum — Awaiting publication confirmation", self.addendum(root.name, name))
		for channel in CHANNELS:
			self._confirm(root, channel, subject="addendum", addendum=name)
		self.assertEqual(frappe.db.get_value("Tender Addendum", name, "status"), "Issued")
		failures += self.check("Addendum — Issued", self.addendum(root.name, name))

		# a supplier clarification from a registered candidate
		frappe.flags.kt_tenders_notice_sync = True
		frappe.flags.kt_tenders_notice_transport = lambda notice: {"result": "Delivered", "provider_reference": f"test:{notice.name}", "failure_reason": ""}
		self.addCleanup(setattr, frappe.flags, "kt_tenders_notice_sync", False)
		self.addCleanup(setattr, frappe.flags, "kt_tenders_notice_transport", None)
		candidate_gateway.register_stand_in_candidate(tender=root.name, user=fx.PRODUCER, bidder_arrangement_id="ARR-TNDT-001", candidate_name="Afya Digital Supplies Limited", notice_address="tenders@afyadigital.example")
		frappe.flags.kt_tenders_clock = "2027-05-26 09:00:00"
		received = clarifications.receive_tender_clarification(tender=root.name, candidate_registration_id="ARR-TNDT-001", question="May the two comparable contracts be from different customers?", received_at="2027-05-26 09:00:00", inbound_event_id="EVT-MATRIX-1", user=fx.PRODUCER)
		failures += self.check("Clarification — Awaiting response", self.clarification(root.name, received["clarification"]))
		failures += self.check("Published — open, clarification pending", self.record(root.name))
		root.reload()
		frappe.flags.kt_tenders_clock = "2027-05-26 11:00:00"
		clarifications.respond_to_tender_clarification(tender=root.name, clarification=received["clarification"], response="Yes. The two comparable contracts may be from different customers.", response_audience="All registered candidates", affects_published_tender=False, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.OFFICER)
		failures += self.check("Clarification — Answered", self.clarification(root.name, received["clarification"]))

		# a material proposal and its cancellation review
		frappe.flags.kt_tenders_clock = "2027-05-28 10:00:00"
		root.reload()
		material = addenda.create_addendum_draft(tender=root.name, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.OFFICER)["addendum"]["name"]
		root.reload()
		addenda.update_addendum_draft(tender=root.name, addendum=material, values={**ADDENDUM, "affected_reference_key": "goods:1:quantity", "revised_value": "300 Each", "reason": "Additional deployment sites require 50 more laptops"}, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.OFFICER)
		failures += self.check("Addendum — material change, Draft", self.addendum(root.name, material))
		root.reload()
		addenda.request_tender_cancellation_review(tender=root.name, addendum=material, reason="Additional deployment sites require 50 more laptops; please consider cancellation.", expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.OFFICER)
		failures += self.check("Addendum — cancellation review requested", self.addendum(root.name, material))
		failures += self.check("Cancel Tender — review requested", self.cancellation_screen(root.name))

		# cancellation
		frappe.flags.kt_tenders_clock = "2027-06-04 14:00:00"
		root.reload()
		cancellation.cancel_tender(tender=root.name, ground="INADEQUATE_BUDGET", reason="The confirmed budget available for this procurement is insufficient to proceed.", expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.AO)
		failures += self.check("Cancelled — obligations due", self.cancellation_screen(root.name))
		failures += self.check("Cancelled — record", self.record(root.name))
		self.assertEqual(failures, [], "\n".join(failures))

	def test_segregation_and_requisition_correction_leave_no_dead_end(self):
		failures: list[str] = []
		# the combined-responsibility person prepared and submitted: another
		# HOPF and another AO hold the decisions and are named
		root = self._started(officer=fx.BOTH)
		self._save(root, officer=fx.BOTH)
		submitted = lifecycle.submit_tender_for_approval(tender=root.name, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.BOTH)
		root.reload()
		failures += self.check("Awaiting procurement approval — preparer holds HOPF", self.review(root.name))
		# §10.7: the conflicted HOPF waits on the eligible one and is told why, in the one line
		step = read.get_tender_review(tender=root.name, user=fx.BOTH)["guidance"]["next_step"]
		self.assertEqual((step["kind"], step["sentence"]), (ns.KIND_WAITING, "You cannot approve a Tender Version you prepared or submitted."))
		approved = lifecycle.approve_tender_package(tender=root.name, expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.HOPF, task=submitted["task"])
		root.reload()
		failures += self.check("Approved — preparer holds AO", self.publication_screen(root.name))
		self.assertTrue(approved["task"])

		# a Requisition correction on a Draft
		fx.wipe_all()
		root = self._started()
		correction.request_requisition_correction(tender=root.name, reason="The authorised battery-runtime requirement must be corrected before this Tender can continue.", expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.HOPF)
		failures += self.check("Requisition correction requested", self.record(root.name))
		self.assertEqual(failures, [], "\n".join(failures))

	def test_the_departmental_author_sees_who_is_correcting_the_requisition(self):
		root = self._started()
		correction.request_requisition_correction(tender=root.name, reason="The authorised battery-runtime requirement must be corrected before this Tender can continue.", expected_record_version=root.record_version, idempotency_key=fx.key(), user=fx.HOPF)
		author = frappe.db.get_value("Requisition Version", frappe.db.get_value("Tender", root.name, "requisition_version"), "prepared_by")
		step = read.get_tender(tender=root.name, user=fx.OFFICER)["guidance"]["next_step"]
		self.assertEqual(step["kind"], ns.KIND_WAITING)
		self.assertIn(frappe.db.get_value("User", author, "full_name"), step["holder"]["people"])
		self.assertTrue(step["headline"].endswith(".") and "is correcting the requisition" in step["headline"])
		journey = read.get_tender(tender=root.name, user=fx.OFFICER)["guidance"]["journey"]
		self.assertEqual([s["marker"] for s in journey["stages"]][0], "blocked")
