# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""Wizard state enum — API contract §8 (canonical for services/API)."""

from __future__ import annotations

# API §8 primary states
DRAFT = "DRAFT"
IN_CONFIGURATION = "IN_CONFIGURATION"
VALIDATION_FAILED = "VALIDATION_FAILED"
READY_FOR_REVIEW = "READY_FOR_REVIEW"
RETURNED_FOR_CORRECTION = "RETURNED_FOR_CORRECTION"
PROCUREMENT_REVIEW = "PROCUREMENT_REVIEW"
TECHNICAL_REVIEW = "TECHNICAL_REVIEW"
LEGAL_REVIEW = "LEGAL_REVIEW"
APPROVED_FOR_TENDER_CREATION = "APPROVED_FOR_TENDER_CREATION"
BOUND_TO_TENDER = "BOUND_TO_TENDER"
PUBLISHED = "PUBLISHED"
ADDENDUM_REQUIRED = "ADDENDUM_REQUIRED"
SUPERSEDED_BY_ADDENDUM = "SUPERSEDED_BY_ADDENDUM"
CANCELLED = "CANCELLED"

ALL_STATES = (
	DRAFT,
	IN_CONFIGURATION,
	VALIDATION_FAILED,
	READY_FOR_REVIEW,
	RETURNED_FOR_CORRECTION,
	PROCUREMENT_REVIEW,
	TECHNICAL_REVIEW,
	LEGAL_REVIEW,
	APPROVED_FOR_TENDER_CREATION,
	BOUND_TO_TENDER,
	PUBLISHED,
	ADDENDUM_REQUIRED,
	SUPERSEDED_BY_ADDENDUM,
	CANCELLED,
)

DELETABLE_STATES = {DRAFT}

KPI_IN_CONFIGURATION = {IN_CONFIGURATION}
KPI_VALIDATION_FAILED = {VALIDATION_FAILED}
KPI_READY_FOR_REVIEW = {READY_FOR_REVIEW}
KPI_RETURNED = {RETURNED_FOR_CORRECTION}
KPI_PUBLICATION_READY = {APPROVED_FOR_TENDER_CREATION, BOUND_TO_TENDER}

OVERDUE_ELIGIBLE_STATES = {
	IN_CONFIGURATION,
	VALIDATION_FAILED,
	RETURNED_FOR_CORRECTION,
	READY_FOR_REVIEW,
}

STATE_LABELS = {
	DRAFT: "Draft",
	IN_CONFIGURATION: "In configuration",
	VALIDATION_FAILED: "Needs action",
	READY_FOR_REVIEW: "Ready for review",
	RETURNED_FOR_CORRECTION: "Returned for correction",
	PROCUREMENT_REVIEW: "Under review",
	TECHNICAL_REVIEW: "Under review",
	LEGAL_REVIEW: "Under review",
	APPROVED_FOR_TENDER_CREATION: "Approved for preview",
	BOUND_TO_TENDER: "Publication ready",
	PUBLISHED: "Publication ready",
	ADDENDUM_REQUIRED: "Addendum required",
	SUPERSEDED_BY_ADDENDUM: "Superseded by addendum",
	CANCELLED: "Cancelled",
}

INITIATION_PLANNING = "PLANNING_INITIATED"
INITIATION_DASHBOARD = "DASHBOARD_CREATED"

DEFAULT_WIZARD_STEPS = (
	("TENDER_IDENTITY", 1, "Tender Identity"),
	("STD_CONFIG_OVERVIEW", 2, "STD Configuration Overview"),
	("TENDER_PROFILE", 3, "Tender Profile"),
	("TDS", 4, "Tender Data Sheet"),
	("IT_REQUIREMENTS", 5, "IT Requirements"),
	("IMPLEMENTATION_SCHEDULE", 6, "Implementation Schedule"),
	("SYSTEM_INVENTORY", 7, "System Inventory"),
	("PRICE_SCHEDULE", 8, "Price Schedule"),
	("EVALUATION_SETUP", 9, "Evaluation Setup"),
	("FORMS_AND_EVIDENCE", 10, "Forms and Evidence"),
	("SCC", 11, "SCC / Contract Carry-Forward"),
	("VALIDATION_REPORT", 12, "Validation Report"),
	("REVIEW_AND_APPROVAL", 13, "Review and Approval"),
	("RENDER_PREVIEW", 14, "Render Preview"),
	("PUBLICATION_READINESS", 15, "Publication Readiness"),
)


def state_label(state: str) -> str:
	return STATE_LABELS.get((state or "").strip(), state or "")
