# Copyright (c) 2026, KenTender and contributors
# For license information, please see license.txt

"""Procurement Handoff Card — visible handoff artifact at module boundaries (ADR-PLC-002; not legal source of truth)."""

from __future__ import annotations

import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import now_datetime

from kentender_procurement.procurement_lifecycle.evidence_links import (
	parse_validate_and_normalize_evidence_links,
)
from kentender_procurement.procurement_lifecycle.handoff_card_status import HANDOFF_CARD_STATUS_VALUES
from kentender_procurement.procurement_lifecycle.technical_refs import parse_validate_technical_refs_json


class ProcurementHandoffCard(Document):
	def before_validate(self):
		if self.is_new() and not self.generated_at:
			self.generated_at = now_datetime()

	def before_insert(self):
		if not self.generated_at:
			self.generated_at = now_datetime()

	def validate(self):
		"""R1-005 — guardrails only; R3 services own authoritative module state.

		R1-010 / ADR-PLC-002: this DocType must **never** persist changes to source modules
		(Demand, Procurement Package, TM2 Tender, …). Stale/conflict handling uses
		``procurement_lifecycle.source_module_authority`` helpers — handoff fields only.
		"""
		if (self.status or "") not in HANDOFF_CARD_STATUS_VALUES:
			frappe.throw(
				_("Status must be a standard handoff card value (pack §6.3)."),
				title=_("Invalid handoff status"),
			)
		if not (self.handoff_code or "").strip():
			frappe.throw(_("Handoff Code is required."), title=_("Invalid handoff"))
		if not (self.generated_by or "").strip():
			frappe.throw(_("Generated By is required."), title=_("Invalid handoff"))
		if not (self.next_action or "").strip():
			frappe.throw(_("Next Action is required."), title=_("Invalid handoff"))

		self._require_json_object(_("Locked Summary"), self.locked_summary)
		self._require_json_object(_("Passed Forward Summary"), self.passed_forward_summary)
		self._validate_evidence_links_json()

		if self.blockers_json not in (None, ""):
			self._require_json_scalar(_("Blockers"), self.blockers_json, allow_list=True, allow_dict=True)
		self._validate_technical_refs_json()

	def _validate_technical_refs_json(self) -> None:
		"""R1-007 — optional JSON; size-capped (``technical_refs`` module)."""
		try:
			normalized = parse_validate_technical_refs_json(self.technical_refs_json)
		except ValueError as exc:
			frappe.throw(str(exc), title=_("Invalid technical references"))
		self.technical_refs_json = normalized

	@staticmethod
	def _coerce_json(value):
		if isinstance(value, str):
			return frappe.parse_json(value)
		return value

	@classmethod
	def _require_json_object(cls, label, value) -> None:
		parsed = cls._coerce_json(value)
		if not isinstance(parsed, dict):
			frappe.throw(_("{0} must be a JSON object.").format(label), title=_("Invalid JSON"))

	def _validate_evidence_links_json(self) -> None:
		"""R1-006 — pack §6.4 shape, JSON storage contract, and size limits (see ``evidence_links``)."""
		try:
			self.evidence_links_json = parse_validate_and_normalize_evidence_links(self.evidence_links_json)
		except ValueError as exc:
			frappe.throw(str(exc), title=_("Invalid evidence links"))

	@classmethod
	def _require_json_scalar(cls, label, value, *, allow_list: bool, allow_dict: bool) -> None:
		parsed = cls._coerce_json(value)
		ok = (allow_dict and isinstance(parsed, dict)) or (allow_list and isinstance(parsed, list))
		if not ok:
			frappe.throw(_("{0} must be JSON (object or array).").format(label), title=_("Invalid JSON"))
